### ISSUE TITLE
MonolithicImplementation model elements that are copied should be assigned a different UUID

### ISSUE THREAD

**Issue by elder4p** [ZeligsoftDev/CX4CBDDS#10]
A MonolithicImplementation model element child of a package that is copied and pasted elsewhere in a model will have the same UUIDs for the worker functions/operations internal to it as the MonolithicImplementation element it was copied from. The UUIDs in the copy are not unique. This does not appear to be a problem so far with our CodeGenUtil scripts that use the UUIDs in the *.taginfo.xml files generated for each, since users will typically have a different component name and location despite the identical UUIDs. But, ideally the UUIDs in two separate MonolithicImplementation model elements should be made unique - either when the copy is made, or due to a subsequent automatic or manual operation.

**Comment by elder4p** [comment]
A patch was produced while investigating this. It is attached here for further review.

[0001-WorkerFunctions-need-new-UUIDs-when-MonolithicImpl-i.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/3208096/0001-WorkerFunctions-need-new-UUIDs-when-MonolithicImpl-i.txt)

**Comment by tuhin-github** [comment]
Fixed with #22
