### ISSUE TITLE
Error when copying deployment plans duplicating components and connectors

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#105]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When copying a deployment plan, deployed components and connectors are duplicated outside of the assembly. To reproduce, take the BasicPubSub model, copy the deployment plan, then paste it. View that the components and data spaces have been duplicated in the left pane

**Comment by ysroh** [comment]
Created a new bug to the Papyrus core.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=561667

**Comment by ysroh** [comment]
This should be fixed now

**Comment by J75880** [comment]
Took the BasicPubSub model, copied the deployment plan, then pasted it. Viewed that the components and data spaces were no longer duplicated in the left pane. So, this issue has been fixed.
