### ISSUE TITLE
Error when attempting to remove Uses List item when editing Port Type

### ISSUE THREAD

**Issue by J75880** [ZeligsoftDev/CX4CBDDS#109]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
If you open a model and go into the ports folder, then right click on a PortType to edit the PortType and attempt to delete an item from the Uses List, the use list item appears to be deleted from the GUI and in the model. However, if you right click on the same port and click to edit the PortType again, then the previously deleted item appears to be in the list still. I'm not sure if this is just an incorrect display or if it's not truly deleting the item, but the item should be deleted.

**Comment by ysroh** [comment]
This should be fixed now.

**Comment by J75880** [comment]
This issue has been resolved.
