### ISSUE TITLE
Repair Module Instantiation operation should not delete the documentation data

### ISSUE THREAD

**Issue by elder4p** [ZeligsoftDev/CX4CBDDS#11]
The "Repair [All] Module Instantiation[s]" operation has an unfortunate side effect of deleting any comments a user may have added to the Properties "Documentation" tab for a repaired ModuleInstantiation model element. The repair operation should ensure that any Documentation tab property content on a ModuleInstantiation is restored after it is repaired.

**Comment by elder4p** [comment]
Some clarifications:



1. What model elements would require this? Is it everything that can become an IDL file?
**a** - I believe so. At the very least, allowing pre-processor commands on everything would be useful

2. For each case above, where, exactly, in the generated IDL file would the customizations appear?
**a** - The use case inspiring this request is for the pre-processor commands to be near the top of the IDL File. I do not have a use case that needs the commands anywhere else at the moment, but I can't rule out that possibility for the future

**Comment by elder4p** [comment]
A patch (attached) was prepared during investigation. The patch has not yet been evaluated for consistency with the answers to the questions above.

[0001-Preserve-comments-when-running-Repair-All-Module-Ins.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/3208184/0001-Preserve-comments-when-running-Repair-All-Module-Ins.txt)

**Comment by tuhin-github** [comment]
Fixed with #21
