### ISSUE TITLE
Adding to Uses/Provides List for a PortType should place items within the PortType in model

### ISSUE THREAD

**Issue by J75880** [ZeligsoftDev/CX4CBDDS#110]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When attempting to add to the Uses/Provides List for a PortType, the usage or provides item will be created correctly and added to the model, but it isn't placed within the PortType. It's instead placed at the same level as the PortType. I would expect that the PortType would act as the "parent directory" and these item be placed within that "directory".

So, if you go to create a PortType in a model and add an interface to both the provides and uses list, then you'll be able to see this.

**Comment by J75880** [comment]
So, if you go to create a PortType in a model and add an interface to  uses list, then the newly created Usage relationship still isn't added as a "child" to the PortType as it was before in RSA.

**Comment by ysroh** [comment]
Can you check if the "SimpleDependencyUML" custom is enabled and "SimpleUML" is disabled from Model Explorer custom list?



![image](https://user-images.githubusercontent.com/896503/79871295-236d3b80-83b2-11ea-9ad0-bd58d876ced5.png)


![image](https://user-images.githubusercontent.com/896503/79871429-51eb1680-83b2-11ea-8327-287d771b93d8.png)

**Comment by ysroh** [comment]
You may have different settings so leave them as is. You just need to have SimpleDenpendencyUML is enabled and take SimpleUML out of the list. It should automatically happen when the tool restarts though.

**Comment by J75880** [comment]
Ah. Yes. I see that now. You’re correct. My apologies. It’s working as it should. Sorry about that! I’ll close out that ticket. Thanks!


JONATHAN DANIEL  |  Engineer Embedded Software
Northrop Grumman Corporation  |  Mission Systems
O: 410-765-7682  |  Jonathan.Daniel@ngc.com<mailto:Jonathan.Daniel@ngc.com>
Concourse Building, GW 410, Baltimore MD

**Comment by J75880** [comment]
If you go to create a PortType in a model and add an interface to uses list, then the newly created  relationships are added as a "child" to the PortType as expected.
