### ISSUE TITLE
Deployment editor no longer opens in Papyrus 4.6

### ISSUE THREAD

**Issue by ysroh** [ZeligsoftDev/CX4CBDDS#118]
# **Issue and tracking information**
The deployment editor does not open in the latest Papyrus version.
Steps to reproduce:
1. Install Papyrus 4.6
2. Open BasicPubSub model and try to open the deployment plan.

Papyrus bug#: 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=561870

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
This issue is fixed and tested using Papyrus 4.8. We should be able to move to a newer version if required.

**Comment by j26151** [comment]
Do we think this issue can be closed now?

**Comment by ysroh** [comment]
Yes, I will close this issue.
