### ISSUE TITLE
Ability to flag model entity to not generate IDL

### ISSUE THREAD

**Issue by elder4p** [ZeligsoftDev/CX4CBDDS#12]
# Time Tracking  information

# Estimate of time to fix :  

# Actual time spent on fix:   

There are use-cases, specifically with the model libraries, where it would be useful to flag certain model entities as "do not generate". In this use-case, we would like the entity to not have a file generated for it.  Possibly not be generated as part of a different file either, in the cases where something would be generated as part of a module's IDL.

**Comment by elder4p** [comment]
Some clarifications:

1. What model element types would this apply to?
**A** - The use case for this request was in our projects when we extend some of the DDS connectors. These would attempt to create new redundant IDL that was already created somewhere else. It would be nice, possibly at a module layer to request it but also at individual interfaces.

2. Can you give an example of "not generated as part of a different file"? 
**A** - There was another use case where an interface was being generated in an IDL file of its own while also being generated within the IDL of a module. This led to two version of the same interface and we had to hand edit one of them away.

**Comment by CharlesAtZelig** [comment]
Added time tracking fields on 2019-09-30 @ 14:15

**Comment by CharlesAtZelig** [comment]
Added time tracking fields

**Comment by J17359** [comment]
I'm going to close a few of these older issues that we may not want done before other things in the issue list. I don't want to cause confusion by leaving them up here. We still have them in our internal backlog and will reopen here once funding allows.
