### ISSUE TITLE
Add modeling and idl generation support for doxygen tags before and after model entities

### ISSUE THREAD

**Issue by elder4p** [ZeligsoftDev/CX4CBDDS#13]
# Time Tracking  information

# Estimate of time to fix :  

# Actual time spent on fix:   

---

An improvement that allows Doxygen tags to be injected before and after a model entity is generated in IDL would be useful in reducing the amount of hand editing that is required on IDL files.

**Comment by elder4p** [comment]
Clarification questions:

1. What model elements would this apply to? 
**A** - I think all of them. We have a lot of cases where it would be useful to tag elements as parts of different doxygen groups. I don't think this needs to be a "Doxygen" specific thing, rather, it could just be a field of text that gets placed before a IDL is generated and text that gets placed after the IDL is generated (like before and after an interface, or method, or attribute).  In fact, if this was in place, it might replace the need for the special pre-processor command capability above as we could place pre-processor commands in this text field as we wished.

2. Would a new field be required in the DDS4CCM properties tab? Or could the 'Documentation' properties tab be used for this? (The answer will depend on whether 'Documentation' is already being used for other purposes.)
**A** - We use documentation in order to comment things already for doxygen. But it isn't powerful enough to allow us to document after the IDL element. The reason we need to comment/document after an IDL element in this case is to close doxygen tags/grouping

**Comment by CharlesAtZelig** [comment]
Added Time tracking fields on 2019-09-30 @ 14:11

**Comment by J17359** [comment]
I'm going to close a few of these older issues that we may not want done before other things in the issue list. I don't want to cause confusion by leaving them up here. We still have them in our internal backlog and will reopen here once funding allows.
