### ISSUE TITLE
Exceptions opening a model

### ISSUE THREAD

**Issue by eposse** [ZeligsoftDev/CX4CBDDS#130]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

Opening a model results in several exceptions. While they are only visible in the Error Log, it's not clear what their consequences are. 

Two of these exceptions may be harmless as they relate to State Machine diagrams and Interaction Overview diagrams, which are not used in AXCIOMA, but precisely because of that, they should not appear at all.

The third exception concerns a class missing from base Papyrus (org.eclipse.papyrus.uml.properties.constraints.HasStereotypeConstraint) but required by one of the Papyrus Compare bundles (org.eclipse.papyrus.revisiontool). It may also be harmless, but it is unclear so it should be investigated.

#### Steps to reproduce

1. Open the Error Log view (Window > Show View > Error Log)
1. Delete existing log entries (Click the "Delete log" button, a red [X] on the top-right corner of the Error Log view.
1. Import the BasicPubSub_new project from the git repo's example folder
1. Open the BasicPubSub_new model (BasicPubSub/ModelFiles/BasicPubSubPapyrus)

#### Expected result

The model opens with no exceptions or errors in the log.

#### Actual result

Several exceptions are thrown with error log entries. See the attached log.

[exceptions.log](https://github.com/ZeligsoftDev/CX4CBDDS/files/4623587/exceptions.log)

**Comment by ysroh** [comment]
Can you create a bug against the appropriate Papyrus component if this is not our problem?

**Comment by eposse** [comment]
With our build, which includes Papyrus Compare, there are three exceptions, but with a previous build that did not include Papyrus Compare and this was installed separately, only two exceptions.

These exceptions are:

```
java.lang.ClassNotFoundException: org.eclipse.papyrus.uml.diagram.statemachine.custom.helpers.advice.PseudostateKindInitializerAdvice cannot be found by org.eclipse.papyrus.uml.service.types_4.1.0.201906121718

java.lang.ClassNotFoundException: org.eclipse.papyrus.uml.diagram.interactionoverview.edit.advices.CallBehaviorActionAsInteractionEditHelperAdvice cannot be found by org.eclipse.papyrus.uml.service.types_4.1.0.201906121718

java.lang.ClassNotFoundException: org.eclipse.papyrus.uml.properties.constraints.HasStereotypeConstraint cannot be found by org.eclipse.papyrus.revisiontool_0.7.0.qualifier
```

The last exception is the one that happens when Papyrus Compare is included in our build.

**Comment by eposse** [comment]
The first two exceptions mentioned in the previous comment where already known to happen in plain Papyrus. See bugzilla: [Bug 548029](https://bugs.eclipse.org/bugs/show_bug.cgi?id=548029).

That bugzilla was reported with Papyrus 4.3, and it is marked as fixed, but the gerrits show a date in late June 2019, after the release of Papyrus 4.4, so we will still see these while we are based on 4.4.

However I'm not closing this issue, since the third exception seems to be linked to our inclusion of Papyrus Compare.

**Comment by eposse** [comment]
It turns out that the third exception (`java.lang.ClassNotFoundException: org.eclipse.papyrus.uml.properties.constraints.HasStereotypeConstraint cannot be found by org.eclipse.papyrus.revisiontool_0.7.0.qualifier`) only happens in the development environment as it is caused by the `org.eclipse.papyrus.revisiontool` plugin from the papyrus-collaborativemodeling repo which hosts Papyrus Compare, but this plugin is not included in the Papyrus Compare feature that we deploy, so it never occurs in Papyrus CX.

Nevertheless, the exception happens because the plugin is missing a dependency to `org.eclipse.papyrus.uml.properties` in its MANIFEST.MF, but it is irrelevant for us, therefore I'm closing this issue.
