### ISSUE TITLE
Allow for any generic pre-processor commands in IDL

### ISSUE THREAD

**Issue by elder4p** [ZeligsoftDev/CX4CBDDS#14]
# Time Tracking  information

# Estimate of time to fix :  

# Actual time spent on fix:   

We are finding that having the ability to add any pre-processor commands to model entities would be very useful in reducing the amount of hand editing that is required.  Specifically, the ability to #include things that are not automatically included (and are not model entities already, as that capability does exist).

**Comment by elder4p** [comment]
Answers to clarifying questions:


1. What model elements would require this? Is it everything that can become an IDL file?
**a** - I believe so. At the very least, allowing pre-processor commands on everything would be useful

2. For each case above, where, exactly, in the generated IDL file would the customizations appear?
**a** - The use case inspiring this request is for the pre-processor commands to be near the top of the IDL File. I do not have a use case that needs the commands anywhere else at the moment, but I can't rule out that possibility for the future

**Comment by CharlesAtZelig** [comment]
Added time tracking fields to issue on 2019-09-30 @ 14:08

**Comment by J17359** [comment]
I'm going to close a few of these older issues that we may not want done before other things in the issue list. I don't want to cause confusion by leaving them up here. We still have them in our internal backlog and will reopen here once funding allows.
