### ISSUE TITLE
Unable to create Case Labels from CX Properites tab

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#143]
# **Issue and tracking information**
When creating/assigning labels for CX Unions, we would go the properties tab, click the CX tab (below UML), click the pencil near Label, and add a label. However, the add button does nothing now. Instead I have to go create a label in the profile tab.

At a minimum we would like Add button mentioned above to work. However, what we would really like is that when the user has specified the switchType, the user should be able to select an appropriate label instead of needing to type one in themselves.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
Fixed

**Comment by ysroh** [comment]
Can you please close this issue if verified?

**Comment by j26151** [comment]
This issue can be closed
