### ISSUE TITLE
Deployment property value for sequence not cleaned up when sequence become empty

### ISSUE THREAD

**Issue by ysroh** [ZeligsoftDev/CX4CBDDS#163]
# **Issue and tracking information**
Deployment properties for sequence should clean up themselves when the sequence value is empty. 
This does not affect functionality. 

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
This issue should be fixed as it leaves unused folders that are no longer being used and causes warning dialog saying there are multiple elements with same name.

**Comment by J17359** [comment]
If you think you can finish this today, please work. We'll be creating our release candidate on Monday so if we can get this into your latest "papyrus" branch by then, that would be awesome!

**Comment by ysroh** [comment]
Sure. I will get it done today.

**Comment by ysroh** [comment]
Fixed
