### ISSUE TITLE
Client Server connection IDL generation adds parameter for return type to param list

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#178]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
All CORBAOperations have a return type and a parameter list. It appears that we have always had the "return type" as a parameter of sorts that we would call the "ReturnParameter" and type it as such. However, since the DDK changes, IDL generation creates a parameters in the parameter list for the return type and this is incorrect.

**Comment by j26151** [comment]
I have verified this is fixed.

**Comment by ysroh** [comment]
I assume I can close this issue as Eric verified fixed.
