### ISSUE TITLE
Hide incorrect menu items

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#180]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

Our users are/will be confused by the options "Validation" and "Model Refactor" that are provided by Papyrus. Since we do not want our users to use them at all, we would like these removed from this menu. We realize this might be a preference change (which would have to be done on our end), but we aren't sure, and ask that you investigate the fix.

**Comment by ysroh** [comment]
Can you provide me some feedback on this commit? I removed the Papyrus validation menu and moved some CX menu items to the existing Papyrus menu. Can you please take a look at the menus and let me know if you have any comments?

**Comment by J75880** [comment]
I think it looks good.
