### ISSUE TITLE
Java WorkflowInterruptedException: Couldn't find operation 'addIncludesFor(idl::specification)' for xpand2::Type

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#181]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When generating IDL on a model library I get the following error:
Java WorkflowInterruptedException: Couldn't find operation 'addIncludesFor(idl::specification)' for xpand2::Type

This worked correctly before the DDK update.

**Comment by ysroh** [comment]
Can you please let me know which model library it is?

**Comment by j26151** [comment]
This a new, SNA created Model library. Not one of the Model libraries provided by you. I can send the model library in a few minutes

**Comment by j26151** [comment]
[CCM_LRT.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/5169723/CCM_LRT.zip)

**Comment by ysroh** [comment]
@j26151 Thanks

**Comment by j26151** [comment]
@ysroh This appears to be fixed now in the most recent changes you made, but the commit log was never linked to this issue. Can you confirm that this should be fixed (and I don't something strange going on)

**Comment by ysroh** [comment]
Yes, the last commit was for this issue. Somehow I didn't link it correctly.

**Comment by j26151** [comment]
Then this is fixed as well. Thank you
