### ISSUE TITLE
Refactor rename CORBA Domain to CX Domain and rename CORBA prefix to CX in all stereotype names

### ISSUE THREAD

**Issue by ysroh** [ZeligsoftDev/CX4CBDDS#185]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
The menu action "Create CX model from UML" to create a Papyrus model from a UML model will perform the CORBA to CX prefix migration during the model creation. However, you need to close all open editors and run this action again on models that are already migrated to Papyrus previously. 

![image](https://user-images.githubusercontent.com/896503/93237512-3bbd6880-f74e-11ea-9840-8c77a993e1a9.png)

**Comment by ysroh** [comment]
[SNA_Int.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/5256517/SNA_Int.zip)
@J75880  Here is the fixed SNA_Int model.

**Comment by J75880** [comment]
This has been fixed and can be closed out.
