### ISSUE TITLE
Unable to use new project options "New CCM Model/Project"

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#189]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When attempting to create a model or project using CX's OMG CCM wizards, an exception occurs.

**Comment by j26151** [comment]
Additionally, if I create a Papyrus model instead, the model requires a migration immediately after creation in order to validate.

**Comment by ysroh** [comment]
I might have already removed the wizard and fixed the validation issue in the latest commit as part of #185 fix. Can you please verify?
You need to migrate models if you use the latest build.

**Comment by J75880** [comment]
This is no longer an issue. It appears as though you did fix this issue in a previous commit. So, this issue can be closed.
