### ISSUE TITLE
Edge Case when refactoring rename CORBA prefix to CX in all stereotype names

### ISSUE THREAD

**Issue by J75880** [ZeligsoftDev/CX4CBDDS#194]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
So, there appears to be an edge case when attempting the migration steps for the refactor of the stereotype names. For some projects, it seems as though the CORBA prefix isn't refactored to CX in certain cases, but the model will validate. Yet, IDL generation will fail. I've attached a project that reflects this edge case. The Example zip folder contains a fully migrated project where in the Operation of the Example Interface, the Return Parameter is still a CORBALong. The Example_unmigrated zip folder
contains the same example prior to ANY migration to the project (so it hasn't been converted to axcioma, etc.) for a basis of comparison. 

[Example.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/5300037/Example.zip)

[Example_unmigrated.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/5300039/Example_unmigrated.zip)

**Comment by ysroh** [comment]
@J75880 Can you use the latest to migrate your model and let me know what you get on your Error log view?

**Comment by ysroh** [comment]
You should see something like this.
![image](https://user-images.githubusercontent.com/896503/97353262-35043400-186a-11eb-8ab7-c6f1b3697137.png)

**Comment by J75880** [comment]
So, it seems like this is no longer an issue. I must have been using an outdated CX version and didn't realize it or something. This issue can be closed out.
