### ISSUE TITLE
Modification of Sequence/Array member types does not inform eclipse that the model has changed

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#197]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

When modifying the type for a "member" element of a Sequence or Array, the model is not recognized as "dirty" which means that we cannot save the model afterwards. There is a workaround for this by modifying the type that you want and then modifying something else in the model that does make the model "dirty". This seems to occur anywhere that you modify a "type" and not an "idlType"

**Comment by j26151** [comment]
I have verified this fix. This issue can be closed.

**Comment by ysroh** [comment]
Fix verified
