### ISSUE TITLE
When creating a new Papyrus model, remove the package import for UML Primitive Types

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#199]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When creating a new model with the AXCIOMA architecture context, the model is populated with two package imports, CXPrimitives and UML Primitive Types. We would like the UML Primitive Types to not be imported by default.

**Comment by ysroh** [comment]
@J17359 Looks like this will won't take long to fix. Can I work on this until you approve more issues to work on?

**Comment by j26151** [comment]
@ysroh Yes, please work this ticket. I will get with @J17359 on Monday to prioritize more tickets for you. Thank you for these rapid improvements!

**Comment by ysroh** [comment]
@j26151 Thanks.

**Comment by j26151** [comment]
I have verified this fix, thank you.

**Comment by ysroh** [comment]
Verified and closing
