### ISSUE TITLE
RPM version behind ZIP version

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#206]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
I noticed from your Travis CI build of the "papyrus" branch that while your ZIP looks to be versioned correctly after the bump to 2.1.0 (https://travis-ci.org/github/ZeligsoftDev/CX4CBDDS/builds/747079284#L7573) your RPM still is at 2.0.0 (https://travis-ci.org/github/ZeligsoftDev/CX4CBDDS/builds/747079284#L7591). Could you please bump the version in the spec file too?

**Comment by ysroh** [comment]
I've updated the version. Thanks

**Comment by J17359** [comment]
Thanks @ysroh ! Feel free to close this issue out.
