### ISSUE TITLE
Models with Null Elements cannot be converted to AXCIOMA

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#218]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When migrating models where components have ports that are untyped, due to issues with model library changes, the SNA migration step to convert the model to AXCIOMA fails. Switching the architecture context does not seem like a valid step and produces corrupted model types. We would like Zeligsoft to provide more information if it cannot convert the model, or convert it anyways with the error.

In the attached model, it requires some SNA DRP model entities, specifically port types. These entities were moved to a different model library and thus the ports need to be retyped. When this situation happens, the uml file can be converted to a CX model, but it cannot be converted to AXCIOMA, and the "convert to AXCIOMA" option just fails, silently. Users have tried "hacking" this by manually switching the architecture context, which causes even more problems.  The solution here would be for CX not to fail to convert the model to AXCIOMA silently, and to instead alert the user to the problem so that it can be solved before converting.

[reproduceMigrationIssue.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/6063722/reproduceMigrationIssue.zip)

**Comment by ysroh** [comment]
I think we should validate the model before converting model to AXCIOMA since it is the only way that broken links can be detected. I've added validation into this action.

![image](https://user-images.githubusercontent.com/896503/111207764-64f56f00-85a0-11eb-98fe-dd5a64cf643c.png)

Please let me know if this is ok.

**Comment by ysroh** [comment]
@j26151  Just let you know that I haven't committed the fix yet. I will do that if the solution is acceptable. Thanks and let me know if you have any comments or think of any problems with this solution.

**Comment by j26151** [comment]
@ysroh I think validating before migrating is a good way to tackle this. This will force users to fix these issues before they can continue on with migrating.

**Comment by ysroh** [comment]
@j26151  Thanks. I will merge my fix after verifying one more time.
