### ISSUE TITLE
Automatically recreate diagrams when migrating models from 1.X to 2.X

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#219]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
We would like the team to do a technical spike to see what it would take to recreate model assembly diagrams when converting between RSA and Papyrus. We understand that the information is lost when going from EMX -> UML. Unfortunately, we have many, many assemblies where losing the diagram appearance would result in many hours of effort to recreate the assemblies each time the model is migrated.

We imagine that a solution may require changes being made to RSA to allow for exporting of the information from an EMX to possible a ".di" file, and we are open to something like that if it is necessary.

**Comment by J17359** [comment]
We'd like your team to keep this investigation to 40 hours max. We're just looking for options on a path forward before we request the specific implementation.

**Comment by ysroh** [comment]
Here is my suggestion for the diagram migration.

Here is a use case scenario to migrate diagram layout.

1. User exports RSA model to UML using newly provided menu like one below.
![image](https://user-images.githubusercontent.com/896503/110530939-fbc9b380-80e8-11eb-8f13-1c433209bbfe.png)
 
We will need to keep layout information of all diagram elements as a EAnnotation.
So exported UML will contain UML + diagram layout annotation.

2. User opens Papyrus and do normal migration process same as before.
3. User creates a Composite Structure diagram under assembly and open the diagram
4. User will right click on a diagram and run "Import Diagram Layout"
    This action will transfer layout from RSA to Papyrus.

![image](https://user-images.githubusercontent.com/896503/110532411-c756f700-80ea-11eb-8c44-dd3011a3af16.png)

This scenario assumes that user will migrate RSA model to Papyrus from the scratch. It means that you need to abandon already migrated Papyrus model if you need to import diagram layout.

I've tested a few thing to make sure this scenario would work. 
What we need to do is.

in RSA:
1. Implement export to UML to export RSA model to UML and transform diagram annotation to GMF notations so they can be loaded from Papyrus

in Papyrus:
2. Implement import layout action which will layout all diagram elements according to the layout information saved from RSA. We need to figure out how to scale coordinates as well.


My estimation for this work is three weeks.

**Comment by J17359** [comment]
Thanks for the detailed estimate @ysroh! I'll bring this up today at our backlog grooming meeting to see what management decides is the next priority.

**Comment by ysroh** [comment]
@J17359 Can you please provide a few good sample models that have some decent size diagrams? 
Diagram migration is a bit more complex than I thought due to different default behaviour like connector routing algorithm. I am trying my best to make the diagram as similar as one from RSA.
I really need more diagram examples so I can achieve that. Thanks.

**Comment by j26151** [comment]
@ysroh Attached is a zip file with 3 models of ours. Discovery is the simplest in that it is just a single assembly. SignalProcessingDataModel is the next largest with 2 assemblies, and the ArtGallery model is the most complex in the zip.
[forZeligsoft.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/6212170/forZeligsoft.zip)

**Comment by ysroh** [comment]
@j26151 Thanks..
