### ISSUE TITLE
Broken comparison/merge

### ISSUE THREAD

**Issue by eposse** [ZeligsoftDev/CX4CBDDS#220]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

Firstly, the way that I am recreating the issue is using the following steps:

1. I pull down the idlpubsub project where the eclipse project is within a folder that exists in the root (i.e. the .project file is not in the root of the git repository)
2. I manually, through the command line checkout one of my branches (deploy_subscriber), then merge another branch on top of it (deploy_publisher). I do this because otherwise eclipse will automatically resolve conflicts.
3. I open up eclipse, and import the project by first importing the git repository, then the project.
4. In the C/C++ perspective, project explorer, I right click on the conflicted model > Team > Model Merge Tool
![image](https://user-images.githubusercontent.com/49879646/109666688-6739e100-7b3d-11eb-8b8d-5d2f23986f09.png)

By doing this multiple time with the older/non-fixed version of the cx-axcioma RPM, I will eventually run out of memory. However, before it does run out of memory I am able to successfully resolve conflicts.
![image](https://user-images.githubusercontent.com/49879646/109667161-db748480-7b3d-11eb-94c7-396a47615f6d.png)

When doing this multiple times with the new/fixed version of the cx-axcioma RPM, I never run out of memory, but the comparison is also broken:

![image](https://user-images.githubusercontent.com/49879646/109667326-08289c00-7b3e-11eb-83ce-842195deef81.png)
Additionally, after the first time, I get a null pointer exception, constantly:
[zeligsoft.log](https://github.com/ZeligsoftDev/CX4CBDDS/files/6069552/zeligsoft.log)

In both scenarios, I was able to use the "git staging" view to merge, and in both scenarios I never hit the memory issues.

**Comment by eposse** [comment]
This was initially reported by @j26151 in Issue #170.

**Comment by eposse** [comment]
@j26151 Can you provide the git repo with your idlpubsub model where you tested? Thanks.

**Comment by eposse** [comment]
It has been agreed to keep the conversation in Issue #170 as the problems seem to happen with the new build introduced by Pull Request #217.

**Comment by eposse** [comment]
It seems like this is due to doing the merge with plain git rather than EGit, leaving EMF Compare to try to make sense of a comparison in a conflicted state. It is not clear if EMF Compare supports this merging scenario.

**Comment by eposse** [comment]
I got confirmation from Philip (the main developer of Papyrus Compare and an EMF Compare contributor). EMF Compare *does not* support this scenario. 

The reason is, as I suspected, that when there is a conflict, 'git merge' leaves the repository and files in a "half-merge" state, a state with conflicts. Plain git doesn't know anything about (EMF) models, it only sees them as plain text files, and whenever there is a conflict, it marks the conflict in the file(s) directly as in this example from the [git docs](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging):

```
<<<<<<< HEAD:index.html
<div id="footer">contact : email.support@github.com</div>
=======
<div id="footer">
 please contact us at support@github.com
</div>
>>>>>>> iss53:index.html
```

(This example is with an HTML file, but the idea is the samle for .uml files which are just plain text XMI files.)

Since such markers are directly included in the XMI (.uml) file(s), then the file(s) is no longer a valid model file, EMF cannot load it and parse it correctly, and this leads to the model appearing to be "broken".

Philip says that it is theoretically possible to implement support for this workflow, but that it isn't implemented now and it would probably be quite some effort.

This means that for now at least, the only workflow supported is via the EGit UI.

Simon mentioned that there is a command-line interface to EGit. I haven't found any, and the EGit docs do not mention it, but there is a command-line interface (CLI) to JGit, the Java implementation of git used by EGit. Nevertheless, I don't think it would automatically work, because I don't think JGit is model-aware either. Hence, it would also require some non-trivial amount of work to integrate EMF Compare with the JGit CLI.

**Comment by j26151** [comment]
I am fine with calling this unsupported. Especially the workflow using "Team > Model Merge Tool".

However, when using git merge from the command line, creating the invalid model file. I have successfully, brought that model into eclipse, and opened the model merging tool by double clicking the model in the git staging view. This has brought up a model merge view that looks correct and I have been able to merge the entities that I needed and the resulting model is then valid and correct.

I am not sure how the above works, but regardless, if we want to close this issue now as a "Won't do" because the workflow is unsupported, I am okay with that. If in the future we see that this workflow is an important use case, we can revisit the issue.

**Comment by eposse** [comment]
For the cases where you have successfully opened the model, was there a conflict?

**Comment by j26151** [comment]
Not opened the model, because the model is invalid from the conflicts that the git merge caused. But when I open the model merge tool from double clicking on the conflicted model in the git staging view, the model merge view is created successfully (sometimes with NPEs that seem to not actually cause any issues) and I am able to merge my model .

**Comment by eposse** [comment]
Hmm... Strange. Ok, we'll park this issue for now and may revisit it at some point in the future as you say.

**Comment by ysroh** [comment]
@eposse Is this reproducible using the static profile? If not can you close this issue? Thanks

**Comment by eposse** [comment]
@ysroh This issue was not related to static vs dynamic profile, but rather it was due to using plain git to merge branches instead of EGit, a workflow not supported by EMF Compare. In the preceding messages Eric agreed that we can close it now and revisit in the future if they really need to use plain git.
