### ISSUE TITLE
Batch diagram migration

### ISSUE THREAD

**Issue by ysroh** [ZeligsoftDev/CX4CBDDS#224]
# **Issue and tracking information**
Allow users to migrate all diagrams in a model instead of migrating individual diagram one by one.
It may not be possible to do this in one click but I think it would be possible to do this in two menu actions.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
I have tried to put a fix for this one and it seemed that the fix was working. However, I found out that the fix does not work due to Papyrus's automatic layout happening when the diagram is on focus the first time. Any changes to the diagram before the automatic layout will be lost. Unfortunately, I suggest using the current solution for the diagram migration.

@J17359 Let us know if you want me to work on any other issues, otherwise, I will be working on some other projects.

**Comment by ysroh** [comment]
The current "Refactor-> Model Migration" action will create all composite structure diagrams that require diagram migration so users don't have to navigate to each assembly to create a diagram in order to import RSA diagram layout.
I will close this issue but feel free to let us know if you have any other suggestions on this matter.

**Comment by J17359** [comment]
> The current "Refactor-> Model Migration" action will create all composite structure diagrams that require diagram migration so users don't have to navigate to each assembly to create a diagram in order to import RSA diagram layout.
> I will close this issue but feel free to let us know if you have any other suggestions on this matter.

Thanks @ysroh. We'll go through our backlog and enter some more tickets into GitHub for you to work as you have time.
