### ISSUE TITLE
Allow CodeGenUtil tool to work headlessly with Papyrus

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#227]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**

Zeligsoft CX for Papyrus comes with the same [CodeGenUtil](https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/bundles/com.zeligsoft.domain.dds4ccm.codegen/src/com/zeligsoft/domain/dds4ccm/codegen/utils/CodeGenUtil.java) tool that came with CX for RSA. When using this tool within a graphical environment like inside our CentOS 7.9 development VMs, everything works fine. When we move into an environment where there is no graphical environment, like if we ssh into the same development VM where things worked and run the exact same command on the exact same workspace/projects, we get failures.

Attached are the log outputs of running headlessly with Papyrus within a graphical environment ([graphicalSuccessPapyrus.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/6319014/headlessGraphical.txt)) and within a non-graphical environment ([headlessFailurePapyrus.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/6319015/headlessNonGraphical.txt)). I'll even attach two logs outputs from running the same test with RSA ([graphicalSuccessRSA.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/6319072/rsaOnVmHeadlessGraphical.txt) and 
[headlessFailureRSA.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/6319076/rsaOnJenkinsHeadlessNonGraphical.txt)).

We would like to use this tool in our Jenkins CICD builds if possible (which will be in a non-graphical environment) to pull down a Git project, validate the model(s), generate descriptors and IDL, build, and run. Right now we've committed the descriptors and idl to our Git repo because we don't have a way to generate it headlessly during our CICD builds. Having this would greatly improve our continuous integration framework and negate the need to maintain model generated files in our Git repos.

PS. We call into your CodeGenUtil.java class with a java class of our own. We call our java class via a bash script to make it easier for our users. I will be emailing you copies of these files for your testing purposes (I don't want to post them online here where the whole world can see them 😄).

PSS. Notice that we had to wrap our .java class with a `PlatformUI.createAndRunWorkbench()` call because of difference in how Papyrus and RSA ran headlessly. We'd love suggestions on how to do this without having to actually launch Papyrus as I can't imagine that will ever work on Jenkins...

**Comment by ysroh** [comment]
@J17359 
I would like to clarify a couple of things before investigating this issue. 
Did headless one ever worked in RSA? 
I assume that forwarding X isn't an option to run graphical one over SSH?

**Comment by J17359** [comment]
> @J17359
> I would like to clarify a couple of things before investigating this issue.
> Did headless one ever worked in RSA?
> I assume that forwarding X isn't an option to run graphical one over SSH?
I think I might have used the wrong lingo in my description above. When I way saying "headless" I meant via cmd line. When I was saying "graphical", I meant in a VM with a GUI (graphical) versus sshing into one (non-graphical) like Jenkins operates. I think "headless" generally means "non-graphical" in the programming world, so that's my fault for the confusion.

Going forward with the definition that "headless" means "without a GUI", no, a headless run never worked in RSA. Both Papyrus and RSA throw the following error when attempting to run our stuff in a headless environment:
`!ENTRY org.eclipse.osgi 4 0 2021-04-15 07:44:50.007
!MESSAGE Application error
!STACK 1
org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
...`

I'd have to check if there's a Jenkins plugin out there that supports X forwarding on Jenkins. I've never used one. At first glance, [this](https://plugins.jenkins.io/xvfb/#documentation) looks like it might do what we need, but I'll have to investigate sometime next week. 

Apologies for the wording confusion. I've renamed my attachments links in the description to keep things straight (even though the actual file name of the attachment will remain the same).

**Comment by J17359** [comment]
PS. So I took a few hours this morning to try and get X forwarding to work in Jenkins with no luck (but that doesn't mean that it's impossible). In the meantime, I'd love to hear your take on how we could approach this. This would be a very welcomed enhancement for our CICD infrastructure if we can get it working on Jenkins.

**Comment by ysroh** [comment]
Thanks a lot for the clarification. We are getting swt error since our plugins depend on UI but X is not available. We would need some investigation if it is possible to eliminate dependency to UI from validation and generation which I am even sure it would be possible at the moment. We will discuss this issue among our team and see if we can find a solution.  Thanks.

**Comment by J17359** [comment]
Thanks Young-Soo. Like I said, I'll definitely continue to test whether or not I can get Jenkins to allow X forwarding because if I `ssh -X user@IP` into a machine and run the sna_cx_utilities.sh script which we use to wrap everything, we can indeed generate IDL and validate models.

But it would certainly be easier if we didn't need X forwarding as that's how the default Jenkins behavior operates.

**Comment by ysroh** [comment]
I hope it is not the permission problem with jenkins user. I am not sure if it is possible but you could run jenkins build from command line as jenkins user to see if you have more clue on why it is not working. I remember long time ago I ran jenkins build as jenkins user to figure out some permission problem.

**Comment by ysroh** [comment]
@J17359 Can you please test if you can generate descriptors and IDLs if you disable validation?
It looks like you can generate descriptors and IDLs if you do not invoke validation. 
Here is the modified utilities project.
[cx-utilities-2.tar.gz](https://github.com/ZeligsoftDev/CX4CBDDS/files/6388383/cx-utilities-2.tar.gz)

You can use the "papyrus_headless" branch.

The validation requires some Papyrus plugins to be activated and those plugins require display :(. I am trying to see if I can avoid those plugins to be activated but not sure if it would be possible at all.

**Comment by ysroh** [comment]
Raise a bug ticket against Papyrus: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573219

**Comment by J17359** [comment]
@ysroh I pulled down your `papyrus_headless` branch and the code changes to our code from the tarball you attached and was able to successfully generate IDL and descriptors headlessly with Papyrus. Both still show the "No more handles" error in the Eclipse .log file, but that's not a huge deal since the command executes and returns correctly.

Model validation does not work as you said.

**Comment by ysroh** [comment]
Unfortunately, model validation will not work with headless due to the bug I reported above. I tried to make this work by extending some of the validation classes so we can control over how they handle exceptions when they occur during the validation but I found out that it is not possible due to the way validation classes are written. 

I think the best way to resolve this issue is to fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=573219 because writing our own validation framework would be too much work.

I know it is not ideal but can you survive without validation?

**Comment by ysroh** [comment]
Here is a hack that you can make validation and generation work together.
You need to remove following plugins from Papyrus/plugins directory for headless setup.
I've tested that all worked fine. I think this could be a temporary solution until above Papyrus issue is resolved.

plugins to remove:

org.eclipse.papyrus.uml.diagram.activity_3.4.0.201906121718.jar
org.eclipse.papyrus.uml.diagram.activity.source_3.4.0.201906121718.jar
org.eclipse.papyrus.uml.diagram.interactionoverview_3.0.100.201906121718.jar
org.eclipse.papyrus.uml.diagram.interactionoverview.source_3.0.100.201906121718.jar
org.eclipse.papyrus.uml.diagram.linklf_2.0.100.201906121718.jar
org.eclipse.papyrus.uml.diagram.linklf.source_2.0.100.201906121718.jar
org.eclipse.papyrus.uml.diagram.sequence_5.2.0.201906121718.jar
org.eclipse.papyrus.uml.diagram.sequence.restrictions_1.0.0.201906121718.jar
org.eclipse.papyrus.uml.diagram.sequence.restrictions.source_1.0.0.201906121718.jar
org.eclipse.papyrus.uml.diagram.sequence.source_5.2.0.201906121718.jar
org.eclipse.papyrus.uml.diagram.statemachine_3.1.100.201906121718.jar
org.eclipse.papyrus.uml.diagram.statemachine.source_3.1.100.201906121718.jar

**Comment by ysroh** [comment]
If this is a reasonable solution for now then I will merge headless branch to Papyrus and close this issue. 
Let me know once you test your setup.

**Comment by J17359** [comment]
@ysroh - Sorry I haven't had a chance to test the model validation hack yet. I can certainly test it but I'm not 100% sure we'll be able to do that in our Continuous Integration framework because we'll be running as a generic user on Jenkins but those plugins are installed and owned by the root user so we can't just go removing them mid-run. I might be able to hack something into place if it does work, but I'd love a supported solution from Papyrus if they ever get around to fixing that bug report you opened.

**Comment by ysroh** [comment]
@J17359 the plugins can be removed as root right after Papyrus is installed and will never need those plugins ever again as long as you do not open any diagram from the workbench. If you are using this Papyrus for jenkins only then these diagram plugins are not needed. 

So you remove once after installation that’s it.

**Comment by J17359** [comment]
Ahhh so maybe I generate a cx-for-jenkins RPM in the meantime to support headless model stuff. That's a good idea.

**Comment by J17359** [comment]
> Here is a hack that you can make validation and generation work together.
> You need to remove following plugins from Papyrus/plugins directory for headless setup.
> I've tested that all worked fine. I think this could be a temporary solution until above Papyrus issue is resolved.

@ysroh - My apologies, I'm finally getting around to testing this. I installed Papyrus and the latest cx-axcioma RPM from your `papyrus` branch which looks to have your `papyrus_headless` changes in it per #232. I ran the latest version of our plugins (includes the changes from the tarball you attached a few comments above). I did NOT remove those plugins you listed just yet.
* Generate descriptors - PASS
* Generate idl - PASS
* Validate model - FAIL (as expected)

I then removed those Papyrus plugins you mentioned (moved them to /tmp so I could restore them later). 
* Generate descriptors - PASS
* Generate idl - PASS
* Validate model - PASS

Do those results meet what you expect? I still see `org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]` messages coming out when I run verbosely for what it's worth, but the validations and generations seem to work regardless.

**Comment by ysroh** [comment]
Yes. That’s exactly what I expected. The SWTError is expected as well. It’s coming from a plugin that we have nothing to do with so I didn’t bother removing that plugin. If it bothers you then I can try to remove that plugin as well. The only thing is that if there are dependent plugins to that plugin then we need to remove them as well. 

Hope this works as temporary solution to headless usage.

**Comment by J17359** [comment]
Yeah, I think this is fine for now. We can close this issue but please keep us posted about the Papyrus bug you wrote!

**Comment by ysroh** [comment]
@J17359 Sure. If there are no activities on that bug then at some point we might have to fix it ourselves and provide the source code to Papyrus team to review and commit. Let’s wait and see for now. Thanks
