### ISSUE TITLE
Can not navigate between assemblies and subassemblies

### ISSUE THREAD

**Issue by rgs424** [ZeligsoftDev/CX4CBDDS#246]
# **Issue and tracking information**

Hyperlinking of assemblies:  When dragging an assembly onto a parent assembly's diagram, it should automatically create a link to the diagram of that sub-assembly so that when a user doubled clicks on it in the parent diagram, it opens up the child assembly.  This functionality is missing. 

while it can manually be recreated through a multi-step non-obvious process, it should be done by default.  BTW, this is the process needed:

double click on child assembly instance located on parent diagram.  This brings up Manage Hyperlinks dialog.
Alternatively, right click on the child assembly → Navigate → Modify Hyperlinks
Click green + and select Specific Object
Select the diagram associated with the child sub-assembly.  This adds it to the list of hyperlinks in the Hyperlinks tab.
Switch to the Default Hyperlinks tab.
Click on the previously selected diagram under Available hyperlinks and then click the yellow arrow pointed towards the right to move it to the Default Hyperlinks column and click Okay.

![image](https://user-images.githubusercontent.com/13985583/119513692-6da5b680-bd42-11eb-98c0-97fb9902c2a7.png)
### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
@J17359 Do you want me to work on this ticket first?

**Comment by j26151** [comment]
@ysroh Yes please. This is a pretty big issue for our users.

**Comment by ysroh** [comment]
Double click on a sub-assembly part should open the assembly diagram of the sub-assembly part.

**Comment by rgs424** [comment]
Would it be helpful to provide you a zip file containing my workspace?

**Comment by ysroh** [comment]
I am sorry that I wasn’t clear. I committed the fix and merged to papyrus branch so it should work if you test this using the latest build.

**Comment by rgs424** [comment]
ah ok thank you!!

**Comment by j26151** [comment]
I have verified this has been fixed. Thank you.
