### ISSUE TITLE
Symbol for subscribe port flips based on location

### ISSUE THREAD

**Issue by rgs424** [ZeligsoftDev/CX4CBDDS#247]
# **Issue and tracking information**

I added a subscribe port to a component. Then I dragged it to a new location and the symbol inverted. This is reproduceable.

In the 2 pictures below, you can the port symbol inverts when clicking the up/down arrow button once.

![image](https://user-images.githubusercontent.com/13985583/119524762-ebba8b00-bd4b-11eb-8e42-2c212ad6a415.png)

![image](https://user-images.githubusercontent.com/13985583/119524827-fa08a700-bd4b-11eb-83ee-906711f4f5eb.png)

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
Fixed and merged to Papyrus branch.

**Comment by J17359** [comment]
Tested and verified on our end. This issue can be closed, thanks @ysroh !
