### ISSUE TITLE
Delegate port contains permanent arrow

### ISSUE THREAD

**Issue by rgs424** [ZeligsoftDev/CX4CBDDS#248]
# **Issue and tracking information**

This may be related to another issue (SNA-246), but when I create a delegating port, it contains an ARROW that won't go away. It is this this way  as soon as I add the port to the diagram. This makes it difficult for a user to see the port type. 

![image](https://user-images.githubusercontent.com/13985583/119528124-f0cd0980-bd4e-11eb-984f-42973f7a3a1a.png)

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
Fixed and merged

**Comment by J17359** [comment]
Tested and verified on our side. This issue can be closed, thanks again!

**Comment by ysroh** [comment]
Thanks
