### ISSUE TITLE
A single CX4CBDDS baseline with two different installables

### ISSUE THREAD

**Issue by tuhin-github** [ZeligsoftDev/CX4CBDDS#25]
We(SNA) are working in two baselines; a maintenance 1.x baseline with ACE+TAO+CIAO+DAnCE support and a new 2.x baseline with AXCIOMA support. We see ourselves maintaining the 1.x baseline for another year or two while SNA 2.x gains adoption once released. As such, we’ll want to keep the SNA 1.x baseline at the CX 1.5.x level. If we move to CX 1.6.x, we’d be providing AXCIOMA support prematurely and lose the marketability of our new SNA 2.x baseline. As you’ll see in the spreadsheet, I’ve added a column titled “NGC request for CX version delivered in” with 1.5.x and 1.6.x as the two options. To reiterate, I see the association between SNA and CX as the following:
	•	SNA 1.x -> CX4CBDDS 1.5.x
	•	SNA 2.x -> CX4CBDDS 1.6.x
We would like the fixes for most bugs found in 1.5.x to be included in both 1.5.x and 1.6.x CX baselines. New features and enhancements will primarily only go into the 1.6.x CX baseline unless our users strongly desire it in the SNA 1.x baseline (like model merging improvements if any are made that are not tied specifically to the new development tool). I could not find a 1.5.x milestone/branch in GitHub so this may be something we need to add.

**Comment by tuhin-github** [comment]
Proposed approach:
	•	Keep a single code base
	•	Produce two separate installables from the same source/build: ATCD-only (aka SNAv1) and ATCD+AXCIOMA (SNAv2)
 
The difference between the two would be minuscule: an extra plugin/fragment that enables AXCIOMA UI contributions. I believe there are only 2 or 3 UI contributions that we have to hide/enable in order to do this.
 
Adopting this strategy has several advantages:
	•	We avoid the cost of maintaining two branches. (Just about every issue we have addressed recently affects both branches.)
	•	AXCIOMA early adopters (who I presume are also the key support people for the SNAv1 users) will be confident that their installation is compatible with SNAv1 users, without having to keep two separate CX versions installed.
	•	Updating an SNAv1 user to SNAv2 is a trivial task.

**Comment by tuhin-github** [comment]
**More from email conversation:**

"Other than potentially hiding any extra AXCIOMA UI contributions, a common CX baseline that supports both ATCD and AXCIOMA was hopefully conveyed in the SOW language for the last sub-contract to cover AXCIOMA additions.  Users should be able to install CX 1.6.x and continue using SNA1.  At least that was the intent per requirements in the AXCIOMA part of the SOW." - Mark

"I think we are all of the same understanding. A single 1.6.x baseline with two types of installables should work for our use-case. As long as we (SNA) have the build instructions to produce the different installables, I think we’ll be able to provide 1.6.x to both SNA 1 and SNA 2 customers, with the SNA 1 customers ONLY getting the ATCD pieces and the SNA 2 customers getting both ATCD and AXCIOMA." - Michael

**Comment by J17359** [comment]
> 
> 
> **More from email conversation:**
> 
> "Other than potentially hiding any extra AXCIOMA UI contributions, a common CX baseline that supports both ATCD and AXCIOMA was hopefully conveyed in the SOW language for the last sub-contract to cover AXCIOMA additions.  Users should be able to install CX 1.6.x and continue using SNA1.  At least that was the intent per requirements in the AXCIOMA part of the SOW." - Mark
> 
> "I think we are all of the same understanding. A single 1.6.x baseline with two types of installables should work for our use-case. As long as we (SNA) have the build instructions to produce the different installables, I think we’ll be able to provide 1.6.x to both SNA 1 and SNA 2 customers, with the SNA 1 customers ONLY getting the ATCD pieces and the SNA 2 customers getting both ATCD and AXCIOMA." - Michael

"I would like to add that the request is slightly more generic.

One of the features we discussed was improving model merging, and ideas for addressing this including moving to a text-based model.  Such a change would be pretty large, and require migration tools.  Not something we would want to enforce on an effort that is more mature.

The point being, some changes being discussed are largely invisible or minor to adopting efforts, and others are more invasive.  We need to make sure we can support both.  It’s hard for me to imagine that SOME of the changes we are discussing would not necessitate the need for multiple branches within the CX product." - Kyle
