### ISSUE TITLE
Comments on Papyrus CX model elements are extremely difficult to read and edit

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#252]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
This is a critical blocker in the Papyrus CX tool which will prevent its use for defining new or modified architectures for an upcoming need. All documentation in IDL and Doxygen ICDs is generated from these comments, so they need to be easily readable and editable.

Comment documentation text fields on existing model elements, found in numerous Property pane locations and popup dialogs, are displayed as single lines of text that extend beyond the right edge of a text box, if longer than the text box width.  It is not possible to read comments longer than this width, or to edit them.  Advancing the cursor does not scroll the text, and no horizontal scrollbar is available.

A simple Word Wrap feature such as found in MS Windows Notepad would fix this issue and make comments on model elements readable and editable.

**Comment by ysroh** [comment]
@J17359 I will work on this issue first as Issue #248 might take a little longer to figure out.

**Comment by J17359** [comment]
> @J17359 I will work on this issue first as Issue #248 might take a little longer to figure out.

Agreed. #247 and #248 are much lower on the priority list (hence me not marking them as "ngc: approved to work" yet)

**Comment by ysroh** [comment]
![image](https://user-images.githubusercontent.com/896503/120542822-8d2f8580-c3b9-11eb-8632-8ee48f8443ab.png)

@J17359 Do you think adding a simple text area at the end of CX properties view would work?? I could not find a way to remove the existing Comments tab.

**Comment by J17359** [comment]
> @J17359 Do you think adding a simple text area at the end of CX properties view would work?? I could not find a way to remove the existing Comments tab.

I think it's much better than before, but I think having the comments tab persist might cause user confusion. If this is the only thing we can do to provide them with a better interface for comments, I'm all for it. But would definitely prefer to avoid having them stumble onto the comments tab where this is not the case.

**Comment by ysroh** [comment]
@J17359 Agreed. I think I can find a way to reuse the existing comment tab. I will let you know soon. Thanks

**Comment by ysroh** [comment]
@J17359 As I was looking into actual code for UML comments I found out that the rich text editor was available through the preference page so I enabled it by default.
Please let me know if this works out, thanks.

**Comment by J17359** [comment]
> @J17359 As I was looking into actual code for UML comments I found out that the rich text editor was available through the preference page so I enabled it by default.
> Please let me know if this works out, thanks.

Thanks @ysroh ! I just built the latest CX RPM internally and will test today. I'll report back here after.

**Comment by J17359** [comment]
@ysroh - I've verified that this fix looks good during my testing. Before we close this issue, however, I'd like to demo this new functionality to the architect who asked for the fix to make sure it works for him. Once I verify that, I'll respond back here. Thanks again for the quick turnaround!

**Comment by ysroh** [comment]
Thanks.
