### ISSUE TITLE
Deployment Editor not resolving assemblies correctly

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#253]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
When you drag an assembly into the “Configure” pane of the Deployment Editor, it should expand to show its relevant connections and components. However it currently does not. In the below picture, we see BPS_asm_2 dragged into the Configure pane from the Model Explorer, but it does not expand like the BPS_asm above it.  You can work around this by right clicking the Deployment, selecting Model Refactor-> Repair Deployment, however this only expands the top level directories. If you have nested assemblies, the nested assemblies and their components will not appear. Please view the attached BPS zip file for further clarification.
![image](https://user-images.githubusercontent.com/46937599/121039462-190d2d00-c77f-11eb-820e-27649228dcbe.png)
[BPS.tar.gz](https://github.com/ZeligsoftDev/CX4CBDDS/files/6610001/BPS.tar.gz)

**Comment by ysroh** [comment]
Fixed and merged.

**Comment by J17359** [comment]
Feel free to close this issue. We've verified it works on our end. Thanks!

**Comment by ysroh** [comment]
Thanks
