### ISSUE TITLE
Fix issue with additional empty space being added after specifying a connector type in the CX pane

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#260]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
When typing ports in the SNA 2.X modeling tool, typing data spaces can cause an odd bug causing the contents of the CX pane to be drastically spaced to the right.
![image](https://user-images.githubusercontent.com/46937599/122919398-2ead5580-d32e-11eb-87be-ec454c002cd7.png)

**Comment by ysroh** [comment]
@J17359 Can you please share some more details on how to reproduce this issue? There might be an error log causing this to happen.

**Comment by J17359** [comment]
> @J17359 Can you please share some more details on how to reproduce this issue? There might be an error log causing this to happen.

I'll need @j26151 to help with that. He was the original reporter of this ticket (on our side) so he may have an environment set up already somewhere...

**Comment by j26151** [comment]
I have not been able to reproduce this on my end. I would suggest we close this issue and we can write a new one if we ever encounter this again.

**Comment by ysroh** [comment]
Please keep the error log if it happens again. Thanks.
