### ISSUE TITLE
Generate IDL should work at different levels in model

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#261]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
Generate IDL (and descriptors) used to work at different levels in model.  It can be done on a component or a message or a module, but not on a package (like a defn package) or a connector package.

**Comment by ysroh** [comment]
Fixed and merged to Papyrus branch

**Comment by j26151** [comment]
This looks fixed on our end. Thank you.

**Comment by ysroh** [comment]
Thanks
