### ISSUE TITLE
Creating a "Connector Default Value Binding" does not modify the model

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#263]
# **Issue and tracking information**
Creating a "Connector Default Value Binding" does not appear to do anything to the model and does not provide the ability to configure defaults for a DDS_Event (or anything else)

To reproduce, follow these steps on the model in the attached BPS project:

1. Open the BasicPubSub model in ModelFiles
2. Navigate to assemblies/Deployment/descriptors
3. Right click on the "ExmaplesDomain" > "Add CX" > "Connector Default Value Binding

In our testing, step 3 does nothing. The model doesn't show any changes either that need to be saved.

[BPS.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/6710705/BPS.zip)

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by j26151** [comment]
@ysroh Please investigate this as soon as you can. Thank you

**Comment by ysroh** [comment]
Fixed and merged to Papyrus branch.

**Comment by j26151** [comment]
This looks fixed on our end. Thank you for the fast turnaround. This issue can be closed.

**Comment by ysroh** [comment]
Thanks
