### ISSUE TITLE
New Export tool for keeping assemblies has bad links to referenced models.

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#266]
# **Issue and tracking information**
Before we had the assembly diagram information fix, we would export all of our models using the export tool and choosing the UML export wizard. After the assembly diagram information feature was added we were to just click "Export Tools > Export to UML" instead. However, this causes issues with any model that is referencing another model.  Here is a scenario:

ModelA.emx depends on nobody. ModelB.emx references type definition in ModelA.emx

If we export ModelB.emx using the UML export wizard, this will cause both ModelA.emx and ModelB.emx to be export as UML files with all of ModelB's references to ModelA set to the uml path.

If we export using the "Export Tools > Export to UML" on ModelB.emx, only ModelB.uml is created and it references ModelA.emx

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
@j26151 I just want to clarify this. So you want to keep the references to the EMX file from the exported UML file, right?

**Comment by j26151** [comment]
@ysroh  When we import ModelB.uml and ModelA.uml, into Papyrus, we want all of the references to be satisfied and correct when using the "Export Tools > Export to UML". This does not happen today, because all references that ModelB.emx had to ModelA.emx are retained, in the newly export ModelB.uml file as "ModelA.emx", which is wrong, because once we import it into Papyrus, ".emx" files do not exist.

Maybe to put it more bluntly, if I export an RSA model with the expectation of it working in Papyrus, the newly exported model should not have any references to ".emx" files, only ".uml" files.

The export wizard within RSA does this correctly, albeit without the assembly diagram layout information.

**Comment by ysroh** [comment]
Fixed and merged to master branch.

**Comment by j26151** [comment]
Thank you, this works on our end. You can close this.

**Comment by ysroh** [comment]
Thanks
