### ISSUE TITLE
Improve setting unbounded strings and generated error messages

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#269]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
Unbounded strings can be set by setting the bounds to Unlimited, but in RSA you were able to leave the value as null and it work correctly. It would nice if this behavior was added back in. But, currently if a user attempts to create an unbounded string and leaves the bound field null, then the model will validate, but it will be unable to generate IDL and doesn't give a very good indication of what the problem is especially in larger models. This should either not validate or provide a more descriptive error message (see screenshot for non-descriptive error message).
Note: what's especially bad about this is you might have done this as one part of a large set of changes, and maybe generated IDL days later, and with this output you do not have a clue where to even begin looking.
![image](https://user-images.githubusercontent.com/46937599/125966313-c32e023c-7df2-411d-80d1-694692d78485.png)

**Comment by ysroh** [comment]
@J17359 I just tested and the null bounded string does not validate in RSA. I suspect that some validations do not kick in due to some refactoring done in the CORBA domain. I will check these validations and add them back in.

**Comment by ysroh** [comment]
![image](https://user-images.githubusercontent.com/896503/126174808-e66ad655-889c-4f85-82ec-a3f360bc4533.png)

**Comment by ysroh** [comment]
I figured out that there was an issue with the constraint provider for the multiplicity elements. The validation should work correctly now.

**Comment by j26151** [comment]
Verified on our end, thank you. This issue can be closed.

**Comment by ysroh** [comment]
Thanks
