### ISSUE TITLE
Add support to CX for extendable types

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#284]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
With RemedyIT adding support for DDS extendable types to AXCIOMA, we need a small modification to our modeling tool to support this new option. RemedyIT recommends that an "extensibility" radio button be added to all union and structure/message types. This radio button will have the options "final" and "appendable" with "final" being the default selection. When generated to IDL, all structs and unions shall have `@final` or `@union` prepended to them like so:
```
@final
struct ShapeType { 
   /// This field contains the color of the shape. 
   color_type color; //@key
 }; //@TopLevel()
```

**Comment by ysroh** [comment]
Should we prepend @final and @union or @appendable??
Can you please check if the example below is correct?

/// @brief CXModule7 
module CXModule7 {

    /// @struct CXStruct1
    @appendable (or should it be @union as metioned in the description?)
    struct CXStruct1 {
    }; //@top-level false
};

#endif // CX_CXMODULE7_PACKAGE6_IDL

**Comment by jwillemsen** [comment]
It should be `@final` or `@appendable`, see https://github.com/RemedyIT/ciaox11/pull/268

**Comment by ysroh** [comment]
Got it, thanks.

**Comment by ysroh** [comment]
Fix merged to Papyrus branch. Tooling and IDL generation related to extensibility is supported except IDLImport. Issue #303.

**Comment by ysroh** [comment]
Thanks
