### ISSUE TITLE
Add check to determine if model needs migrating 

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#287]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
In the RSA version of CX, when a model needed migrating, the user would be told this when they opened the model.  Now they only know if they run Validation. Add a check when opening the model to see if it needs migrating and prompt the user.

**Comment by eposse** [comment]
@J17359 I've merged this fix. The user gets a message on the console and the log if the model needs migration when the model is opened.

Let me know if we can close this.

**Comment by j26151** [comment]
I see the message on the CX console, which I think is a good start. But we would prefer this to be some sort of pop up event. Otherwise, it is extremely easy to miss on the console.

**Comment by eposse** [comment]
@J17359 @j26151 Sorry for the radio silence. I have been very busy for the last week.

I have updated the code with a pop-up that will alert the user and ask if they want to migrate now or not. However it is not fully working quite yet. The actual migration action doesn't seem to be doing anything on the test model. (I'm using the AMI4CCMExample from the repo). I'm currently debugging it to see why this is happening.

**Comment by ysroh** [comment]
Fixed. Removed option to migrate directly from the dialog.

**Comment by j26151** [comment]
I have verified that this is fixed on our end.
