### ISSUE TITLE
CodeGenUtil validation produces different results for same .emx file

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#290]
### NOTE:
**This is occurring in RSA, but any fixes done for this ticket might need to get forwarded to the `papyrus` branch if applicable.**

This problem is also very difficult to describe, so please let me know where I can clarify (we can also jump on a phone call if needed).

### Problem Overview:
* Problem 1
  * Cmd line model validation shows WARNING level messages that do not show up when validating the exact same model in the exact same Eclipse workspace when invoking the model validation from within Eclipse. The WARNING level messages are treated as failures (as I agree they should), so we wind up with an invalid model when validating via cmd line but a valid model from within Eclipse.
* Problem 2
  * Cmd line model validation with different combinations of projects in a workspace produce different validation results on the same model.

The hope is that we can be just as confident in the cmd line model validation/IDL generation as we can when doing the same thing through the Eclipse GUI. The cmd line way of validating/generating will allow us to script this sort of work to reduce manual effort from our users as well as provide a way of automating this process through our continuous integration infrastructure (Jenkins).

### Source Code for Reference:
This is very closely related to https://github.com/ZeligsoftDev/CX4CBDDS/issues/227 so please look there for more background into how we are validating models via cmd line. Essentially, we use the bash script below, which calls our ModelUtilities.java class, which is wrapping your CodeGenUtil class.

[Attached ](https://github.com/ZeligsoftDev/CX4CBDDS/files/7099137/sna_cx_utilities.zip) are two files:
1. sna_cx_utilities.sh <-- simple bash file that wraps the ModelUtilities.java invocation
2. ModelUtilities.java <-- simple java file that wraps calls into `CodeGenUtil.validateModel()` and the other methods (like for generating IDL and descriptors)

I believe you have access to all the SNA Example projects for RSA and Papyrus already. If not, let me know so I can provide them.

### Reproducing Problem 1:
When running model validation from cmd line on our PSAT example, the model validation throws the following "contains two or more indistinguishable members" WARNING message:
```
# Create Eclipse workspace
/opt/IBM/SDP/eclipse -consoleLog -console -nosplash \
    -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
    -data ~/workspaces-rsa/cmdLineWorkspace \
    -import ~/git/sna/sna_core/Examples/contents/src/PubSubAttachment

# We actually call "sna_cx_utilities.sh -w <workspace> -- -a -v" but it boils down to this:
/opt/IBM/SDP/eclipse -clearPersistedState -consoleLog -console \
    -data ~/workspaces-rsa/cmdLineWorkspace \
    -application com.ngc.sna.cx.utilities.ModelUtilities -a -v

# Returns (the "two or more indistinguishable members" message is the WARNING log level)
Found emx file: ~/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx
Model: file:~/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx Starting...
Model: file:~/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx Completed
Validate: file:~/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx: Warning
        IRJA0137W "<<dDS4CCMModel>> <Model> PubSubAttachment" contains two or more indistinguishable members named "<Package> ports."
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
Result: 1
```

### Reproducing Problem 2:
Even weirder, if I validate this PSAT model via cmd line in a workspace where I have the BPS example, it validates just fine.
```
# Create Eclipse workspace
/opt/IBM/SDP/eclipse -consoleLog -console -nosplash \
    -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
    -data ~/workspaces-rsa/cmdLineWorkspace \
    -import ~/git/sna/sna_core/Examples/contents/src/PubSubAttachment \
    -import ~/git/sna/sna_core/Examples/contents/src/BasicPubSub

# We actually call "sna_cx_utilities.sh -w <workspace> -- -a -v" but it boils down to this:
/opt/IBM/SDP/eclipse -clearPersistedState -consoleLog -console \
    -data ~/workspaces-rsa/cmdLineWorkspace \
    -application com.ngc.sna.cx.utilities.ModelUtilities -a -v

# Returns
Found emx file: ~/git/sna/sna_core/Examples/contents/src/BasicPubSub/ModelFiles/BasicPubSub.emx
Found emx file: ~/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx
Model: file:~/git/sna/sna_core/Examples/contents/src/BasicPubSub/ModelFiles/BasicPubSub.emx Starting...
Model: file:~/git/sna/sna_core/Examples/contents/src/BasicPubSub/ModelFiles/BasicPubSub.emx Completed
Model: file:~/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx Starting...
Model: file:~/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx Completed
Validate: file:~/git/sna/sna_core/Examples/contents/src/BasicPubSub/ModelFiles/BasicPubSub.emx: Info
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
Validate: file:~/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx: Info
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
Result: 0
```

But if I pick a different SNA Example project to import alongside PSAT, say "SignalProcessing", it gets the warning again:
```
# Create Eclipse workspace
/opt/IBM/SDP/eclipse -consoleLog -console -nosplash \
    -application org.eclipse.cdt.managedbuilder.core.headlessbuild \
    -data ~/workspaces-rsa/cmdLineWorkspace \
    -import ~/git/sna/sna_core/Examples/contents/src/PubSubAttachment \
    -import ~/git/sna/sna_core/Examples/contents/src/SignalProcessing

# We actually call "sna_cx_utilities.sh -w <workspace> -- -a -v" but it boils down to this:
/opt/IBM/SDP/eclipse -clearPersistedState -consoleLog -console \
    -data ~/workspaces-rsa/cmdLineWorkspace \
    -application com.ngc.sna.cx.utilities.ModelUtilities -a -v

# Returns
Found emx file: /home/entds.ngisn.com/4j17359/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx
Found emx file: /home/entds.ngisn.com/4j17359/git/sna/sna_core/Examples/contents/src/SignalProcessing/ModelFiles/SignalProcessing.emx
Model: file:/home/entds.ngisn.com/4j17359/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx Starting...
Model: file:/home/entds.ngisn.com/4j17359/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx Completed
Model: file:/home/entds.ngisn.com/4j17359/git/sna/sna_core/Examples/contents/src/SignalProcessing/ModelFiles/SignalProcessing.emx Starting...
Model: file:/home/entds.ngisn.com/4j17359/git/sna/sna_core/Examples/contents/src/SignalProcessing/ModelFiles/SignalProcessing.emx Completed
Validate: file:/home/entds.ngisn.com/4j17359/git/sna/sna_core/Examples/contents/src/SignalProcessing/ModelFiles/SignalProcessing.emx: Info
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
Validate: file:/home/entds.ngisn.com/4j17359/git/sna/sna_core/Examples/contents/src/PubSubAttachment/ModelFiles/PubSubAttachment.emx: Warning
        IRJA0137W "<<dDS4CCMModel>> <Model> PubSubAttachment" contains two or more indistinguishable members named "<Package> ports."
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
        Connector "<<connectorStatusListenerConnection>> <Connector>" must connect at least one required interface to a compatible provided interface.
Result: 1
```

**Comment by ysroh** [comment]
@J17359 Is it possible to attach the PubSubAttachment example? We don't have that example. Thanks.

**Comment by J17359** [comment]
> @J17359 Is it possible to attach the PubSubAttachment example? We don't have that example. Thanks.

Sure thing. Here is the example:
[PubSubAttachment.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/7100589/PubSubAttachment.zip)

A caveat though - this PSAT example relies on a PSAT connector model library to be installed or else it'll fail to validate entirely. I'm going to try and get you a reproducer today, but odds are I won't be able to get you one until Tuesday at the earliest (unless @j26151 can help). We have a US Holiday on Monday and I'm scheduled to be off work tomorrow.

**Comment by ysroh** [comment]
I only have PSAT connector model not as a installed library so that would be a problem. If you could send me the jar file or installer for PSAT lib that would save my time. Monday is a Canadian holiday as well and I will be taking some vacations starting later next week. @elder4p and @eposse can work on this if I can't finish before my vacation.

> > @J17359 Is it possible to attach the PubSubAttachment example? We don't have that example. Thanks.
> 
> Sure thing. Here is the example:
> [PubSubAttachment.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/7100589/PubSubAttachment.zip)
> 
> A caveat though - this PSAT example relies on a PSAT connector model library to be installed or else it'll fail to validate entirely. I'm going to try and get you a reproducer today, but odds are I won't be able to get you one until Tuesday at the earliest (unless @j26151 can help). We have a US Holiday on Monday and I'm scheduled to be off work tomorrow.
> 
> For what it's worth, I think the issue arises because the model library we're using in PSAT also contains a "ports" folder which is why the warning shows up when validating (but only sometimes as noted in the issue description).

**Comment by ysroh** [comment]
Can you please send me the CCM_PSAT.uml file for RSA? I only have migrated version to Papyrus. I can create a jar file myself.
Thanks

**Comment by J17359** [comment]
> Can you please send me the CCM_PSAT.uml file for RSA? I only have migrated version to Papyrus. I can create a jar file myself.
> Thanks

Sorry, that's what I'm trying to figure out on my end. I'm not sure I can send that file without approval, but if you said you already have the CCM_PSAT.uml for Papyrus, then this may have just gotten a lot easier. Can you confirm you already have the PSAT model library for Papyrus?

**Comment by ysroh** [comment]
Yes. I already have the PSAT library for Papyrus.

**Comment by J17359** [comment]
### Another data point:

I can reproduce the behavior inside of Eclipse:
1. Import PSAT and BPS projects into workspace
2. Run model validation on **just PSAT**
    1. Model validation shows `0 error(s), 1 warning(s)` (the warning being the same `two or more indistinguishable members named <Package> ports` warning from the cmd line behavior in comments above)
    2. Doesn't matter if validation is invoked via the RSA right-click > Validate option or our SNA plugins menu option that invokes the Zeligsoft CodeGenUtils class
3. All subsequent model validations in this workspace for the same PSAT model pass (assuming you don't close Eclipse)
4. Close/reopen the workspace by clicking `File > Restart`
5. Run model validation again on **just PSAT**
    1. Model validation shows `0 error(s), 1 warning(s)` again
6. Close/reopen the workspace by clicking `File > Restart`
7. Validate **PSAT and BPS at the same time**
    1. Model validation shows `0 error(s), 0 warning(s)`
    2. Doesn't matter if validation is invoked via the RSA right-click > Validate option or our SNA plugins menu option that invokes the Zeligsoft CodeGenUtils class

So it seems to only happen on the **first** time the PSAT model is validated after the workspace is opened (unless you validate it with some other models - and even then, it depends on which models - same as from cmd line). I imagine the call into the CodeGenUtils class from our cmd line tool is essentially opening/closing the workspace every time we run it which mimics the behavior when performing the validation in Eclipse which I just listed.

**Comment by J17359** [comment]
### One more data point:
In Eclipse:
1. Import PSAT and BPS projects into workspace
2. Run model validation on **just BPS**
    1. Model validation shows 0 error(s), 0 warning(s)
3. All model validations in this workspace for the **PSAT model** now pass regardless of combinations (assuming you don't close Eclipse)

So it seems like RSA just needs to run one time or something before validating a model where this `indistinguishable member` warning might be in order for it not to show up on subsequent validations.

**Comment by ysroh** [comment]
Thanks for the detailed info. I suspect that our plugin to disable that validation is never called with PSAT model. I need to figure out that first. I also suspect that the PSAT model is somehow corrupted because there are no two “ports” folder. I will investigate and let you know next week.

**Comment by ysroh** [comment]
After further investigation, I found no way to disable the problematic validation before its first run or persist the settings to disable it when using the command-line version of the Eclipse.

So I have no choice to implement a work-around for CodeGenUtil.validation function.
The workaround is to run a fake validation to disable the validation before the real validation run.
We only need to run the fake validation once before the first validation call.

I've merged the fix to the "papyrus" branch.

Please let me know if this works for you.

**Comment by ysroh** [comment]
I would also suggest using more uncommon folder names in a model library since they fall into the same namespace as other folders in the user model that imports it. For example, that's why the validation complains about two "ports" folders from the PubSubAttachment model.

**Comment by J17359** [comment]
@ysroh - thanks for your hard work over the past few weeks with this ticket! I have successfully validated that both the latest cx-axcioma (papyrus branch) and cx-atcd (master branch) are validating our SNA examples correctly and deterministically (as far as my testing has shown). I think we can close this issue and I will write another if I run into anything else. Thanks again!

**Comment by ysroh** [comment]
Thanks. I will close this one.
