### ISSUE TITLE
Disallow Dynamic Pathmapping on linked workspace models

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#294]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
In papyrus, after we are done modeling and generating artifacts, we run CMake to create build projects that we then compile. When we run CMake we create a new project that we call a "Build project" which builds the "Source Project". This build project requires a eclipse "link" to the entire source project.

This causes the Dynamic Pathmapping feature to complain if the source project contained a model that had a dynamic pathmap as now the eclipse workspace has 2 copies of that model, even though they both resolve to the exact same model in the filesystem and the workspace.  In our plugins, we have a solution to filter out models from the build project which would have solved this problem altogether, however, due to other Eclipse and Cmake idiosyncrasies, these filters get removed "randomly" (not random, but not worth getting into here)

We would like a solution to this that is possibly toggleable, but where the default setting is that the dynamic pathmapping tool will either ignore models that are found via. linking, or, even better, consider all models with the same absolute path/eclipse resource path as the same model and not complain or see them as separate models. 

One caveat here is that we do still need to allow for links in projects to git repositories. That is almost all of our projects reside in locally cloned git repositories. We use eclipse's egit plugin to import them, and thus the imported projects are links to the git repository. 

An easy way to reproduce is to take any model, make it pathmapped, create a new empty project, and import the file as a link into the new empty project.

**Comment by ysroh** [comment]
@j26151 The dynamic pathmap from the linked resource will be ignored if there is the same pathmap already.
You can still use the linked model as a pathmap if there is no existing pathmap.
Please let me know if you find any issues with this fix.

**Comment by j26151** [comment]
@ysroh I have verified that this fixes our issue. Thank you for the fast turnaround!

**Comment by ysroh** [comment]
Thanks for verifying.
