### ISSUE TITLE
Papyrus update site has moved causing error when building CX

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#296]
https://github.com/ZeligsoftDev/CX4CBDDS/blob/078b5c8ffc11c0ed0fcc3d552300224a62d50e53/releng/com.zeligsoft.dds4ccm.configuration/pom.xml#L17 should be `<papyrus.url>http://archive.eclipse.org/modeling/mdt/papyrus/updates/releases/2019-06/`

**Comment by eposse** [comment]
A bit strange. I still see the update site at download.eclipse.org, but with https. Perhaps that's the problem? In any case, the archive URL will likely stick around for longer.

**Comment by J17359** [comment]
Well, maybe I was wrong...turns out that link still does exist but the site.xml has been returning a 502 Bad Gateway error all morning.

**Comment by J17359** [comment]
I'll try https and see if that fixes things (and leave it as `download` instead of `archive`).

**Comment by eposse** [comment]
Sorry, I pushed the commit before reading your message. I've set it to https://archive.eclipse.org. I can change it to https://download.eclipse.org if you prefer.

**Comment by J17359** [comment]
I think all the `http`'s need to get changed to `https` in that properties section. My build looks to be getting further with that modification. I also don't have a preference on `archive` vs `download` but imagine `archive` would persist longer as you stated. 

```diff
<properties>
		<tycho.version>1.3.0</tycho.version>
		<rootdir>${maven.multiModuleProjectDirectory}</rootdir>
		<project.build.sourceEncoding>ISO-8859-1
		</project.build.sourceEncoding>
-		<eclipse-release.url>http://download.eclipse.org/releases/2019-06/
+		<eclipse-release.url>https://download.eclipse.org/releases/2019-06/ 
		</eclipse-release.url>
		<orbit.url>https://download.eclipse.org/tools/orbit/downloads/drops/R20190602212107/repository
		</orbit.url>
-		<papyrus.url>http://download.eclipse.org/modeling/mdt/papyrus/updates/releases/2019-06/
+		<papyrus.url>https://download.eclipse.org/modeling/mdt/papyrus/updates/releases/2019-06/
		</papyrus.url>
-		<cdt-98-repo.url>http://download.eclipse.org/tools/cdt/releases/9.8/
+		<cdt-98-repo.url>https://download.eclipse.org/tools/cdt/releases/9.8/
		</cdt-98-repo.url>
		<emf-compare.url>https://download.eclipse.org/modeling/emf/compare/updates/releases/3.3/R201905300200</emf-compare.url>
		<papyrus-compare.url>jar:file://${rootdir}/releng/deps/org.eclipse.papyrus.compare.p2-0.7.0-SNAPSHOT.zip!/
		</papyrus-compare.url>
	</properties>
```

**Comment by eposse** [comment]
Ok, I've pushed another commit. It looks like the only ones with 'archive' are Papyrus and CDT. The rest are available only on 'download'.

**Comment by eposse** [comment]
I opened pull request GH-297. Once the build finishes I'll merge it.

**Comment by eposse** [comment]
@J17359 So it looks like we've ran out of credits in our Travis account so Travis cancels the build jobs. I am able to build it locally though. So if you are Ok with it, I'll merge the change even though we don't have a "pass" from Travis.

Hopefully we can sort out the Travis credits soon.

**Comment by jwillemsen** [comment]
Would recommend to use github actions, faster, more parallel builds and free. We use it for AXCIOMA and TAOX11 also.

**Comment by J17359** [comment]
> @J17359 So it looks like we've ran out of credits in our Travis account so Travis cancels the build jobs. I am able to build it locally though. So if you are Ok with it, I'll merge the change even though we don't have a "pass" from Travis.

@eposse - Our internal builds are working with the http -> https change. I'm cool with merging this change without Travis if you all are.

**Comment by eposse** [comment]
@J17359 It's merged. Let me know if I can close it now.

**Comment by J17359** [comment]
> @J17359 It's merged. Let me know if I can close it now.

Close away!
