### ISSUE TITLE
Prepare IDL generator to make the toplevel annotation more flexible

### ISSUE THREAD

**Issue by jwillemsen** [ZeligsoftDev/CX4CBDDS#30]
# Time Tracking  information

# Estimate of time to fix :  

# Actual time spent on fix:   

ATCD and AXCIOMA 2 use `@top-level` for IDL structures that are top level for DDS. The `@top-level` annotation is RTI DDS specific and also is non-legal IDL (the - is not allowed in IDL). 

It would be useful for the future when the `@top-level true|false` would be defined through a constant which we could set to a different value (for example `@TopLevel()`)

**Comment by CharlesAtZelig** [comment]
Added time tracking fields on 2019-09-30 @ 13:58

**Comment by jwillemsen** [comment]
https://github.com/ZeligsoftDev/CX4CBDDS/issues/493 will change `@top-level` to `@nested` which is the IDL4 defined annotations for this
