### ISSUE TITLE
IDLImport for extensibility attribute

### ISSUE THREAD

**Issue by ysroh** [ZeligsoftDev/CX4CBDDS#303]
# **Issue and tracking information**

Update IDL import to support extensible objects.
It would take too long to commit Issue #284 with IDL import support, so I am creating a separate ticket for import only.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by j26151** [comment]
When importing the file above, I now get passed the error. The elements look mostly correct except for one small issue:

![image](https://user-images.githubusercontent.com/49879646/137303981-ef66ea2f-3ba7-4768-8087-b8c13b33f4c5.png)

It looks like Unions aren't being placed in the defn package the way the rest of the IDL elements are.

**Comment by ysroh** [comment]
The behaviour is exactly the same in RSA. So I think there was a reason why this was done intentionally. 
Do you want me to look into this and try to fix it or at least find out why Unions are intentionally left out?
