### ISSUE TITLE
EXT: Copying CX elements across models loses stereotype information

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#308]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When copying CX elements within the same model or across models, it appears that some information is lost, specifically, stereotype information, and sometimes this is not recoverable. We would like to be able to copy any number of things, types, templated connectors, components, assemblies, etc...  We have experimented with an interface with operations and parameters as well as a component. Both of these were unable to copy everything correctly. We could recover the interface by stereotyping all of the elements, but the component was not recoverable.

**Comment by elder4p** [comment]
A note on pull request #329. The request patches Papyrus 4.4.0 to include a copy-paste fix that first appeared in 4.6.0. Because of some issues with the Tycho build environment, this patch is not entirely transparent. The build now generates:

- a separate update site `papyrus_v440_patch_2.1.0.*.zip`
- an updated axcioma RPM that installs this update site (in addition to the main one)
- users directly installing `dds4ccm_axcioma_2.1.0.*zip` must now also install the patch. We will update the web site instructions.

We have introduced a general mechanism for patching Papyrus. For some bugs, this is a much better choice than working around issues in CX. Such was the case for some of the copy-paste problems.

**Comment by J17359** [comment]
> We have introduced a general mechanism for patching Papyrus. For some bugs, this is a much better choice than working around issues in CX. Such was the case for some of the copy-paste problems.

Very cool - thanks for the update @elder4p!

**Comment by J17359** [comment]
PS. I left a comment on the spec file. We should uninstall that patch when CX is totally removed from the system via a `yum remove...`. Have you tested upgrading a CX RPM that has already installed that patch with another CX RPM containing that patch? I wonder how yum will handle that. We might need to check in the patch is installed in the `%pre` scriptlet of that spec file and uninstall it if so.

**Comment by J17359** [comment]
PSS. Our latest papyrus branch builds are now failing. See attached log output from our mvn build command.
[mavenBuildError.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/7485692/mavenBuildError.txt)

**Comment by J17359** [comment]
> PSS. Our latest papyrus branch builds are now failing. See attached log output from our mvn build command. [mavenBuildError.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/7485692/mavenBuildError.txt)
> 
> Last working hash: [6823c71](https://github.com/ZeligsoftDev/CX4CBDDS/commit/6823c71c6a6183943549ba276a3cdeea4906ec0b)
> 
> I know very little about maven, but I THINK the upgrade in the tycho version may have caused this.

Sorry for all the comments in a row (the original "PS..." comment still stands about the spec file). But I think I figured out the build error. We were building with Java 8. Tycho was built with Java 11 which cannot be used on 8. We have Java 11 installed, but for some reason the symlinks in /usr/lib/jvm weren't updated to point to the latest installed Java. As soon as I exported the JAVA_HOME env var to the Java 11 JDK, it got past the error. Sorry for the confusion!

**Comment by elder4p** [comment]
@J17359 : I was just thinking that moving to Tycho 2.5 might break your builds. The somewhat confusing 'P2ArtifactRepositoryLayout has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0' message in fact means 'use Java 11, not Java 8'.

Using Java 11 should have no impact out what JVM the final product runs on. That is controlled by specifications in the plug-ins themselves, which all still specify ancient JVMs like 1.6 or 1.7.

Meanwhile, I'll take a look at the RPM definition, and see about uninstalling the patch. Practically, this is no need to uninstall such a patch, unless you want to install an older RPM first. But, I should do that just for consistency.

**Comment by J17359** [comment]
> @J17359 : I was just thinking that moving to Tycho 2.5 might break your builds. The somewhat confusing 'P2ArtifactRepositoryLayout has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0' message in fact means 'use Java 11, not Java 8'.

Yeah I should have Googled before asking the question. Sorry about that!

> Using Java 11 should have no impact out what JVM the final product runs on. That is controlled by specifications in the plug-ins themselves, which all still specify ancient JVMs like 1.6 or 1.7.

Good to know. So we **don't** need to set a `Requires: java-11-openjdk` line in the spec file correct?
 
> Meanwhile, I'll take a look at the RPM definition, and see about uninstalling the patch. Practically, this is no need to uninstall such a patch, unless you want to install an older RPM first. But, I should do that just for consistency.

Yeah I generally try and make the user's system just like it was prior to installing the RPM if at all possible. Even if things _shouldn't_ matter if they stick around.

**Comment by elder4p** [comment]
> Good to know. So we don't need to set a Requires: java-11-openjdk line in the spec file correct?

@J17359 : Correct. No need to change the required JVM.

**Comment by J17359** [comment]
FYI: I just tested an upgrade scenario after generating two RPMs and the upgrade failed since the patch feature group was already installed. Looks like we need to remove it first.

**Comment by elder4p** [comment]
> FYI: I just tested an upgrade scenario after generating two RPMs and the upgrade failed since the patch feature group was already installed. Looks like we need to remove it first.

Testing a fix right now. I'll get you to review it once I'm done. Thanks.

**Comment by ysroh** [comment]
There were a few problems related copy/paste issue, but they are all resolved except one that I reported separately. See Issue #335. Otherwise cross model copy/paste should work. Please let me know if the Diagram copy is gating or not. It looks like we need at least a week to produce a fix for the diagram copy issue.

**Comment by ysroh** [comment]
Since we have a way to patch Papyrus, we do not need to move to a newer version at this time. We will fix Issue #118 after the release so we can move to a newer version when it is time to do so.

**Comment by elder4p** [comment]
So, it looks like we have run into a 'feature' of p2 when uninstalling feature patches, as discussed in P2 [bug 450271](https://bugs.eclipse.org/bugs/show_bug.cgi?id=450271). The bottom line:

- installing a feature patch causes the original version of the patched plug-in to be locally removed.
- running the p2 director uninstallIU command on a feature patch tries to find that original plug-in, but cannot, because, be default, p2 directory will not contact update sites to resolve the missing plug-in
- adding a `-r` option to the p2 director command will correctly uninstall. (See example, below).

This is the uninstall command that works:

`
sudo /opt/Papyrus/papyrus    -application org.eclipse.equinox.p2.director    -nosplash    \
  -uninstallIU com.zeligsoft.papyruspatch.feature.group \
  -r https://archive.eclipse.org/modeling/mdt/papyrus/updates/releases/2019-06/ \
  -vmargs    -Xms512m    -Xmx1024m    -XX:+UseParallelGC    -XX:PermSize=256M    -XX:MaxPermSize=512
`

Question: Is it acceptable to contact an outside update site in order to do the uninstall?

My understanding is that many deployments are to machines with no internet connection. If that is so, then we will have to figure out a way to install a small repo with the original plugin. I see we keep a folder `/opt/cx-axioma` with the repos from which we installed. I can probably figure out a way to create a third repo with the pre-patch-plugin(s). We could then locally address it in the uninstall.

@J17359 : what are our requirements here?

**Comment by J17359** [comment]
> So, it looks like we have run into a 'feature' of p2 when uninstalling feature patches, as discussed in P2 [bug 450271](https://bugs.eclipse.org/bugs/show_bug.cgi?id=450271). The bottom line:
> 
> * installing a feature patch causes the original version of the patched plug-in to be locally removed.
> * running the p2 director uninstallIU command on a feature patch tries to find that original plug-in, but cannot, because, be default, p2 directory will not contact update sites to resolve the missing plug-in
> * adding a `-r` option to the p2 director command will correctly uninstall. (See example, below).
> 
> This is the uninstall command that works:
> 
> ```
> sudo /opt/Papyrus/papyrus    -application org.eclipse.equinox.p2.director    -nosplash    \
>   -uninstallIU com.zeligsoft.papyruspatch.feature.group \
>   -r https://archive.eclipse.org/modeling/mdt/papyrus/updates/releases/2019-06/ \
>   -vmargs    -Xms512m    -Xmx1024m    -XX:+UseParallelGC    -XX:PermSize=256M    -XX:MaxPermSize=512
> ```
> 
> Question: Is it acceptable to contact an outside update site in order to do the uninstall?
> 
> My understanding is that many deployments are to machines with no internet connection. If that is so, then we will have to figure out a way to install a small repo with the original plugin. I see we keep a folder `/opt/cx-axioma` with the repos from which we installed. I can probably figure out a way to create a third repo with the pre-patch-plugin(s). We could then locally address it in the uninstall.
> 
> @J17359 : what are our requirements here?

Yes, we need to handle the use-case where a deployment may not have internet access. We also need to keep in mind that the `%pre`, `%post`, etc. spec file scriptlets run before or after the RPM lays down the actual files. See https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#ordering for great documentation on this.

As such, during my tests, I test the following (at each step verifying that no errors occurred during installation/uninstallation of feature groups):
0. Generate two cx-axcioma RPMs - only differing in the release field version timestamp
1. Install RPM 1 **(tests install use-case)**
2. Uninstall RPM 1 **(tests uninstall use-case)**
3. Install RPM 2 **(tests that uninstall from RPM 1 left no files around that would conflict with future installs)**
4. Uninstall RPM 2 
5. Install RPM 1 (or whatever timestamp in release field is the oldest)
6. Install RPM 2 (or whatever timestamp in release field is the newest) **(tests upgrade use-case)**

**Option 1 (as you suggested to handle the no-internet use case:**
I am seeing the same behavior in that if CX uninstalls the patch, it removes the Papyrus `UML Tools` plugin thereby breaking the Papyrus install. We need some behavior added that can save off that old plugin (to somewhere like `/opt/cx-axcioma` as you suggested) and then reset it during the uninstall of the patch.

**Option 2 (which I don't like):**
If we were to say "the patch is harmless, let's not uninstall it" then we'd still need logic during the patch install to check if it's already been installed. If so, don't install it or else the p2 director will yell at us.

**Comment by J17359** [comment]
> Yes, we need to handle the use-case where a deployment may not have internet access. We also need to keep in mind that the `%pre`, `%post`, etc. spec file scriptlets run before or after the RPM lays down the actual files. See https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#ordering for great documentation on this.

Forgive me for not completing my thought here. My point in stating this was to warn that we need to be careful when we run uninstall/install commands so we don't accidentally uninstall the just installed CX. Notice we don't actually install the **new** RPM's update site in `%post` until after the **old** RPM was uninstalled from Papyrus in `%pre`.

**Comment by ysroh** [comment]
In my opinion, the patch should be considered as part of the Papyrus install. We should install this patch feature once and forget about it rather than uninstall it every time the CX feature is uninstalled. 
How about asking users to install this patch during Papyrus installation? or distributing Papyrus that this patch is already installed?

**Comment by J17359** [comment]
> In my opinion, the patch should be considered as part of the Papyrus install. We should install this patch feature once and forget about it rather than uninstall it every time the CX feature is uninstalled. How about asking users to install this patch during Papyrus installation? or distributing Papyrus that this patch is already installed?

I vote for distributing Papyrus with this already patched. That would be MUCH easier. We distribute Papyrus already (since it's not provided as an RPM) so we could easily add this to our Papyrus spec file. Great suggestion Young-Soo!

**Comment by elder4p** [comment]
All. I will remove the patch installation from the RPM, and leave it to @J17359 to integrate its inclusion in the base Papyrus installation. I'll also update our public readme to clearly show the process: 1) install papyrus, 2) install patch, 3) install CX. I should have a pull request available shortly.

**Comment by J17359** [comment]
> All. I will remove the patch installation from the RPM, and leave it to @J17359 to integrate its inclusion in the base Papyrus installation. I'll also update our public readme to clearly show the process: 1) install papyrus, 2) install patch, 3) install CX. I should have a pull request available shortly.

I'll test this first thing Monday morning. I have to head out of the office early today (noon EST). Thanks everyone for working through this!

**Comment by elder4p** [comment]
@J17359 : Here's a link to the [build associated with the pull request](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/1426473079). I think the artifacts auto-delete after 3 days, but you should be good on Monday morning.

**Comment by J17359** [comment]
Thanks @elder4p. I'll work on getting this integrated into our Papyrus build this morning. Do you think I should copy/paste your latest papyrus_patch .zip file and simply use that or do you expect that patch to change in the future which means I should build that patch .zip from scratch every time I generate the Papyrus RPM?

**Comment by elder4p** [comment]
@J17359 : I expect the patch will be very stable, so you're safe copying it.

**Comment by ysroh** [comment]
This patch is temporary so that we don't need to move to a newer version of Papyrus. We do not need this patch once we move to a newer version.

**Comment by J17359** [comment]
> This patch is temporary so that we don't need to move to a newer version of Papyrus. We do not need this patch once we move to a newer version.

Right. I am testing an internal build of a Papyrus RPM with this patch now. I'm using the zip from the CICD build after your merge: https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/1434855214

**Comment by J17359** [comment]
@ysroh @elder4p @eposse
@j26151 has tested this fix after I generated new CX and Papyrus (w/patch) RPMs. This, along with #287 have been tested and verified that the fix matches our expectations. The only remaining GitHub issue that we'd like before the formal release is #286 which has been worked on for quite some time now. Could we please get a status on that? We **want** that fix but don't **need** that fix before our formal release. 

If you don't think we could have a fix by EOD tomorrow, 11/9/21, then could we at least merge in whatever is there (assuming there's nothing breaking a user's workspace) and then write a follow up ticket for next CX release? If possible, we'd like a release/tag from you by EOD Wednesday (11/10/21) so we can start our internal testing on our SNA software that relies on that version.

**Comment by ysroh** [comment]
Closing this issue as it is verified.
