### ISSUE TITLE
EXT: Assembly diagram shows <<Component>> stereotype

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#310]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
Assembly diagram shows <<Component>> stereotype in the title which is misleading to the average developer. We would prefer for assembly diagrams to show <<Assembly>>

**Comment by ysroh** [comment]
Fix merged to the papyrus branch

**Comment by j26151** [comment]
I have verified this fix. Thank you.

**Comment by ysroh** [comment]
Thanks
