### ISSUE TITLE
Pathmapped models that are modified cause dependent models in the same folder/project to return to path resolution

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#328]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
Project "MyProject", has two models "Model_A", and "Model_B". Model_A has a dynamic pathmap for its model and Model_B is referencing Model_A through that pathmap (i.e. in Model_B's Referenced models pane you can see pathmap://MODEL_A/Model_A.uml). Possible extra requirement: Model_B has a component from Model_A in one of Model_Bs assemblies.

If Model_As component above is modified in some way, like an extra port is added and typed, then a dialog prompts the user to allow changes to read_only Model_B. If this dialog is canceled, then the typing fails. If the dialog is accepted, then Model_B's references to Model_A returns to a platform, path specific reference and not a Pathmapped reference.

**********************************************************************************************************************

In order to reproduce, I am adding a model that contains a modified version of our BPS example. In this example, the ClientServer.uml model has been added to the ModelFiles folder. BasicPubSub.uml has a dynamic pathmap, and ClientServer.uml references BasicPubSub.uml as a dynamic pathmap. ClientServer also has the BasicPublisher_comp added to its assembly diagram.

If you open up BasicPubSub, navigate to BasicPubSub/components/SNA_Examples/BasicPublisher_comp/BasicPublisher_comp and add a new port. Then type that port as a DDS_Listen port:
![image](https://user-images.githubusercontent.com/49879646/139260902-1e431ea4-39df-4390-906d-31589ed5c8ba.png)

[Uploading dpm_issue.zip…]()
You should see the error mentioned above.

**Comment by ysroh** [comment]
Can you please upload the reproducer model again? It says it is still uploading.
I tried to reproduce it using the steps provided with BPS and ClientServer model but I wasn't able to reproduce the problem.

**Comment by j26151** [comment]
[dpm_issue.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/7454452/dpm_issue.zip)
Hopefully it uploads better this time.

**Comment by ysroh** [comment]
Got it, thanks.

**Comment by j26151** [comment]
I have tested this on our end and it appears that the notation file is updated. Additionally, new changes to the dependency model doesn't force updates to the dependent model.

**Comment by ysroh** [comment]
Great!, thanks. I will close this issue. We are still working on the copy/paste issue, and we will let you know the status soon.
