### ISSUE TITLE
Investigate IDL generator reporting files as changed when the model has not changed

### ISSUE THREAD

**Issue by eposse** [ZeligsoftDev/CX4CBDDS#342]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

In Issue #286 we discovered that sometimes the generator will report some files as changed after invoking the IDL generator successively on a model even though the model has not changed at all.

After a long investigation, a problem was discovered in the Xtend generator, where the contents of some generated IDL elements where transferred to other elements leaving several different IDL Specifications being generated for the same model element. See the discussion on #286 for details.

A solution to that issue was to replace the transfer of elements by copies, but unfortunately that generated another problem, as the copy operation didn't copy EAnnotations.

The culprit seems to be com.zeligsoft.domain.ngc.ccm.utils.Copier.copy(EObject) which does the following

```java
		EcoreUtil.Copier copier = new EcoreUtil.Copier();
		EObject result = copier.copy(eObject);
		copier.copyReferences();
```

For some reason, this is not copying EAnnotations of the EObject. While debugging, the input eObject has as eStorage the UML2 CacheAdapter, but the resulting object doesn't. This may or may not be related, but suggests that there is something wrong with the setup.

In any case, it looks like ultimately the problem is due to the Xtend workflow itself. It may need to be rewritten, or may need a major restructuring.

**Comment by ysroh** [comment]
Fixed and merged to "papyrus" branch.

**Comment by ysroh** [comment]
Please verify that this issue can be closed. Thanks

**Comment by j26151** [comment]
I have verified this fix, thank you.

**Comment by ysroh** [comment]
Thanks
