### ISSUE TITLE
Papyrus assembly diagram doesn't update when interface port is added from the model explorer and not the palette

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#346]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
If you go into the BPS assembly diagram and add an interface port to the diagram  from the model explorer (right click on the assembly in the model explorer -> add CX -> Interface Port), it won't show up on the visual diagram until it is closed and reopened.

**Comment by ysroh** [comment]
This should be fixed now. Please confirm if I can close this. Thanks

**Comment by j26151** [comment]
I have verified this is fixed. Thank you.
