### ISSUE TITLE
Make it so that it is not possible to deploy a container process outside of a domain

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#355]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
It should not be possible to deploy a container process outside of a domain (makes no sense) in the deployment plan editor. If you do this accidentally (drag & drop onto open area in Deploy pane), it's also hard to get rid of, since there's no "Undeploy" menu option for it. I you do this accidentally and need to get rid of it, you have to select "Delete" twice on the process instance in the Configure pane, then create a new container process instance. In training classes, this caused deployment errors as well. 

I'm unsure of whether or not this is still an issue in Papyrus but wanted the investigation to take place sooner than later.

**Comment by ysroh** [comment]
This is fixed now and can be closed once verified.

**Comment by j26151** [comment]
I have verified this fix on our end. You can close this issue.

**Comment by ysroh** [comment]
Closing. Thanks
