### ISSUE TITLE
Validate "Is Asynchronous" is checked/unchecked on all components/assembly ports

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#356]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
If a client-side (conjugated) basic InterfacePort on a monolithic component nested inside of one or more parent assembly components has its "Is Asynchronous:" box checked, AND any of the delegated client ports on its parent assembly component tree do NOT have this same box checked, AND a connection is made between the highest level delegated assembly client port and a service port on another component/assembly, then the connection and related artifacts for this AMI4CCM interconnect are not properly generated to a CDP deployment descriptor file. All connections are missing in this case, and there are no AMI4CCM connector component fragment <implementation> or <instance> entries generated into the CDP file either.
 
This request is for a new model Validation error check to ensure that if a client port on a monolithic component has its "Is Asynchronous:" box checked, then all parent assembly component client ports that this port is connected/delegated to must also have their "Is Asynchronous:" box checked.

**Comment by ysroh** [comment]
Added batch validation to check delegate connector compatibility between two ports. Fix merged to papyrus. Please let me know if any of the issues fixed should be back ported to the 2.1 maintenance branch.

**Comment by youngsooroh** [comment]
@j26151 I see. Do you want me to delete/hide "isAsynchronous" check box?? or set it to True by default and disable editing when AMI4CCM is selected??

**Comment by j26151** [comment]
If the "isAsynchronous" check box has absolutely 0 impact on what is generated because the connector type "AMI4CCM" is all that matters for deciding when ayschronous client side artifact generation occurs then I see no reason to keep the check box around at all. 

Additionally, it would be great if we could default the connector type to always be CORBA4CCM instead of needed to select it ourselves each time we add a new port to a component.

**Comment by ysroh** [comment]
The isAsynchronus field is being used during the generation so instead of modifying the generation code, I've added edit helper to automatically set the value according to the connector type and made the attribute read-only. The default connector type will be set to CORBA4CCM connector if the port type is set to an interface. Please let me know if this solution is acceptable.

**Comment by ysroh** [comment]
I also removed the isAsynchronous stereotype from the Interface itself let me know if this is going to be an issue.

**Comment by j26151** [comment]
Sorry for taking so long to respond. I tested this out and everything looks good here. The only thing that I would ask is if its possible to hide the "is Asychronous" check box all together. Or make it more obvious that its a disabled field. The reason I ask this is in the case where the connector type is CORBA4CCM, its really hard to tell that it is disabled so users will attempt to click that checkbox and see that nothing happens. If not, this isn't a huge concern for us, this is already a great improvement.

**Comment by ysroh** [comment]
Absolutely. I will hide the field all together. Thanks

**Comment by j26151** [comment]
I see that isAsynchronous is hidden which is great. My only question left is that when I type a port as AMI4CCM and check the profile tab under properties, the isAsynchronous boolean is set to false. I would expect this to toggle to true with AMI4CCM. Is this field no longer used at all or is false okay in this instance?

**Comment by ysroh** [comment]
I've seen that the value of the stereotype was not refreshed under the profile tab. Can you try to click another object and come back to the same port to see if the value is updated?

**Comment by j26151** [comment]
Clicking off of the object and back on shows it being updated correctly. I would be fine with closing this ticket, but I would like to have that tab refresh immediately. I can't think of other specific instances where this has happened but I know this is not the first time we have seen this in papyrus for other fields. It would be great if the UI was refreshed on its own or accurate when we are viewing it

**Comment by ysroh** [comment]
I will create a separate ticket for the refresh issue and close this ticket, thanks.
