### ISSUE TITLE
Work with CX to upgrade to latest Papyrus

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#357]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
It's always beneficial to target the newest formal versions of software. I imagine [Papyrus 5.2.0](https://www.eclipse.org/papyrus/download.html) has some good bug fixes and improvements in it.

The only thing I'm concerned about is migrating the new CX 2.1.X patch version to this new major release of Papyrus. It certainly makes sense in my head to move to Papyrus 5.2.0 on the latest papyrus branch targeting CX 2.2.0 as that would be a new minor version of CX that should be able to make such a jump to a newer Papyrus. But since our users in SNA 2.1.0 are targeting CX 2.1.X, we'd prefer if we kept some sort of maintenance branch (maybe we call it "papyrus_2.1.X") that we can put important bug fixes back on but leave off some of these new feature requests. I'm willing to discuss this more over the phone or in this ticket if I'm not making total sense.

**Comment by ysroh** [comment]
I made updates so our codebase would work for the latest Papyrus 6.0 version however I am blocked due to Papyrus compare dependency issue. The latest version that the Papyrus compare installs is the 4.8 version so we might have to fork the Papyrus compare and update dependencies ourselves in order to update to the Papyrus version 5.x or 6.x. I will keep you updated on this issue.

**Comment by ysroh** [comment]
Ernesto sent an email to a developer working on the Papyrus compare and found out that they are currently working on a release, but they don't know when it will be ready. I don't expect the release will be ready soon. So we have two options.
1. Upgrade CX to the Papyrus 4.8 for now and upgrade it to version 6.x when the Papyrus compare is available.
2. We fork the Papyrus compare and try to make it work with the latest version and maintain the Papyrus compare ourselves until the official release is available.

Let me know what your preference is.
If you like option 2, then Ernesto can work on the Papyrus Compare.

**Comment by J17359** [comment]
@ysroh - I spoke with @j26151 and he and I agree that sticking with 4.8 for now and upgrading with Papyrus compare is available is what we're comfortable with right now. I'm not sure the up front investment in support hours is worth moving to 6.x if you need to also figure out how to maintain and get Papyrus compare working since no one on our side will be using 6.x until we formally released - which is a long way out from today. Please continue with option 1 above. Thanks!

**Comment by ysroh** [comment]
Sounds good. I will update Papyrus to version 4.8. Thanks.

**Comment by ysroh** [comment]
@J17359 @j26151 

I am upgrading CX to Papyrus 4.8, and I have a quick question.
Do you use the following tools internally? I see these features from your RPM spec, but we don't use these.
I am trying to clean up the dependencies while doing the dependency update to 4.8.

    org.freemarker/2.3.22.v20160210-1233, \
    org.eclipse.tools.templates.freemarker/1.0.0.201812111206, \
    org.eclipse.tools.templates.core/1.1.0.201812111206, \
    org.eclipse.tools.templates.ui/1.1.1.201812111206, \
    org.eclipse.tm.terminal.control/4.5.100.201901312304, \
    javax.xml.stream/1.0.1.v201004272200, \
    com.sun.xml.bind/2.2.0.v201505121915, \

**Comment by J17359** [comment]
> @J17359 @j26151
> 
> I am upgrading CX to Papyrus 4.8, and I have a quick question. Do you use the following tools internally? I see these features from your RPM spec, but we don't use these. I am trying to clean up the dependencies while doing the dependency update to 4.8.
> 
> ```
> org.freemarker/2.3.22.v20160210-1233, \
> org.eclipse.tools.templates.freemarker/1.0.0.201812111206, \
> org.eclipse.tools.templates.core/1.1.0.201812111206, \
> org.eclipse.tools.templates.ui/1.1.1.201812111206, \
> org.eclipse.tm.terminal.control/4.5.100.201901312304, \
> javax.xml.stream/1.0.1.v201004272200, \
> com.sun.xml.bind/2.2.0.v201505121915, \
> ```

@ysroh - I imagine you're talking about the feature list [here](https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L6-L61)? It seems like the only one we're using from that list in our SNA Java plugins is the `javax.xml.stream` package. I just installed Papyrus 4.4.0 and don't see that `javax.xml.stream` package available so I image we need you to keep installing it for us (unless Papyrus 4.8.0 comes with it by default).

**Comment by ysroh** [comment]
@J17359 
I am trying to test CX on Papyrus 4.8 and found out that the right click menus are not aligned and look ugly.
Do you think you can download and run the following version to see if you have the same problem??
Thanks.

https://www.eclipse.org/downloads/download.php?file=/modeling/mdt/papyrus/rcp/2020-06/4.8.0/papyrus-2020-06-4.8.0-linux64.tar.gz

**Comment by ysroh** [comment]
@J17359 @j26151 
I've updated CX to Papyrus version 4.7 instead of 4.8 for now. As mentioned in an earlier comment, the menu items look ugly in version 4.8. I am not sure it is because I have an older version of CentOS so it would be great if one of you could just download version 4.8 and check any context or drop-down menu items to check if they are not aligned in your environment as well.
I think it is still worthwhile to update CX to version4.7. At least, we don't have to deal with the papyrus patch for copy-paste issue. It means that you do not need to install Papyrus 4.4.0 patch before distribution.

I committed my changes to papyrus-v4_7 branch and the build artifacts can be found at the following location.

https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/1726763829

Papyrus 4.7 RCP can be downloaded from this link:
https://www.eclipse.org/downloads/download.php?file=/modeling/mdt/papyrus/rcp/2020-03/4.7.0/papyrus-2020-03-4.7.0-linux64.tar.gz

I've tested the RPM installer but let me know if you have any issues with installation.
Let me know if you find any issues with this upgrade.

**Comment by J17359** [comment]
@ysroh - Sorry for the delay! I can take a look at this today, hopefully, and get back to you on what the right click menus look like for us in 4.8 in our environment. I'll report back once I've had a chance to test things. Thanks!

**Comment by J17359** [comment]
@ysroh My apologies yet again. A lot going on right now. I'm finishing up a task today that needs my immediate attention and then I'll be able to test your code and the papyrus weirdness you were seeing above with 4.8.

**Comment by ysroh** [comment]
@J17359 No problem. Thanks for the update.

**Comment by J17359** [comment]
@ysroh - Ok so I installed Papyrus 4.8.0 and did not see any issues with the right-click menu options. Could you post a screenshot of what you were seeing for comparison or maybe give me a set of steps to run to try and reproduce? The only right-click menu I checked was the one in the Project Explorer view.

I had trouble installing CX into 4.8.0 but hacked something into place to try and get more right-click menu options to test. Assuming I didn't break anything in my hackery, I was able to successfully also test right-click menus in the Model Explorer view for the BasicPubSub model. Again, I didn't notice anything out of whack so a screenshot would be help in comparing.

I'm about to reset my environment and test again with Papyurs 4.7.0.

**Comment by J17359** [comment]
@ysroh - Testing with Papyrus 4.7.0 and your latest CX build from that branch job you linked has been successful. I'm running some more tests this morning but I say we can move forward with the upgrade. I'll report ASAP if I find any bugs.

**Comment by ysroh** [comment]
@J17359 Here is the screenshot of the Papyrus 4.8. I see the menu like this without installing the CX.
If the menu looks good in your environment then I will update CX to 4.8. I just need to update the dependencies so it will probably be ready by tomorrow to test.

![image](https://user-images.githubusercontent.com/896503/151808338-a046f1b0-f80f-424b-ba5e-2ba1c1829e6d.png)

**Comment by J17359** [comment]
@ysroh - I never saw anything like that in my environment, no. I wonder if it's the GTK package you have installed in your version of CentOS throwing things off.

Regardless, I'm ok with moving to 4.8.0 if you are. I'll test again once you're ready for me.

**Comment by ysroh** [comment]
@J17359 That's what I suspected. I will let you know as soon as CX for Papyrus 4.8 is ready. Thanks

**Comment by ysroh** [comment]
@J17359 CX is now updated for Papyrus 4.8. Java 11 is required for this version.
I've tested the RPM installer. Please let me know if you have any issues.
I will merge this branch to papyrus once it is verified.

https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/1774715739

**Comment by ysroh** [comment]
Update merged to papyrus branch.

**Comment by J17359** [comment]
@ysroh - I think this can be closed. I spent the past week migrating all our Java code to Java 11 and Papyrus 4.8.0 with the latest CX from the papyrus branch. I think it's safe to say that everything is working as expected for now and that anything that might crop up could be captured under another ticket. Thanks for all the work on this!

**Comment by J17359** [comment]
@ysroh - Please close this when you get a chance. It was tested on our end. Anything that may arise in the future can spawn a new issue. Thanks!
