### ISSUE TITLE
Adding dynamic pathmap causes headless model validation and IDL generation through CodeGenUtils plugin to fail

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#358]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**
As described in https://github.com/ZeligsoftDev/CX4CBDDS/issues/227, we wrap the Zeligsoft CodeGenUtils plugin you've written with a command line tool to invoke the model validation and IDL generation functionality via the command line. We use that command line script to automate some health checks we perform on our software. Recently, we noticed some models start failing model validation and IDL generation all of a sudden. When the same models were validated and IDL generated in the graphical Papyrus view, everything worked fine. But invoking the validation and IDL generation through the command line tool was failing. It seems to have boiled down to when pathmaps were added to our models.

**Model validation error**
To recreate, import the BasicPubSub and ClientServer models we've provided in past tickets into a fresh workspace. Add a pathmap to the ClientServer model named CLIENT_SERVER (or whatever you want) and then right click on the BasicPubSub model and click Import > Import ICM Model. Select the ClientServer.uml file from the browse dialog. Then add a model element to BasicPubSub typed with an element from the ClientServer model and validate the model graphically. You'll see everything validate. However, when our command line utility calls "com.zeligsoft.domain.dds4ccm.codegen.utils.CodeGenUtil.validationModel()", we get a "Model validation reported error(s)" error - no other feedback on specifics.

**IDL generation error**
When we run the headless IDL generation in some cases, the following errors are displayed. Again, this works without error in the graphical Papyrus using the right click Generate > IDL option.
Error 1:
![image](https://user-images.githubusercontent.com/46937599/148817413-4166ede6-ad5f-43bd-bbba-888ef7315136.png)

Error 2:
![image](https://user-images.githubusercontent.com/46937599/148817464-57427255-2570-481e-a85d-97c8a9f3557d.png)

Error 3:
![image](https://user-images.githubusercontent.com/46937599/148817531-924c091c-08a3-42f9-9d40-8437de4b59b0.png)

**Comment by ysroh** [comment]
I found out that the dynamic pathmap is not loaded automatically during the headless invocation so I manually registered pathamps in the SNA util code. I tested that the headless validation works fine now. Can you please verify this on your side?

**Comment by ysroh** [comment]
[com.ngc.sna.cx.utilities.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/7859118/com.ngc.sna.cx.utilities.zip)

**Comment by J17359** [comment]
Just tested this with BasicPubSub and ClientServer models as described above and both validate successfully.

I'm still getting errors when using more complex models that aren't allowed for export so let me try and get a reproducer I can send you. Stand by.

**Comment by J17359** [comment]
@ysroh - Actually, I think I may have had a bad environment when testing this during my previous comment. Just reporting back here that I think everything is working now but I'm going to run a few more tests before I say to close this ticket. Thanks for your patience!

**Comment by J17359** [comment]
@ysroh This ticket can be closed. Thanks again for the quick turnaround! I've verified our projects are validating as expected with these changes.

**Comment by ysroh** [comment]
That's good news! Thanks. I will close this ticket.
