### ISSUE TITLE
Component Label Appearance

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#374]
# **Issue and tracking information**
Components in diagrams have the following appearance issues that we would like changed if possible. 

1. The migrated component instance's name is in the in the middle of the component and not a top compartment
2. Its symbol is not the component symbol.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by j26151** [comment]
Additionally, when clicking on a component on an assembly diagram and go to the Profile tab under properties, it shows as CCMPart. I would it expect it to be a CCMComponent profile. I'm not sure what the impact of this is, but it should be looked into.

**Comment by ysroh** [comment]
A component instance is a different object than the component definition so they have their own properties and icons. I am not sure if I can change the icon for the component instance or not but I will look into it. I will also look into seeing if I can align the title as well. About the properties tab, I would be really careful and somewhat reluctant to mix properties of two different object types since I know it is going to introduce challenges to make it work since the object selected is not the object you edit. If this is something absolutely required then I will try to put component definition properties under the instance page and will let you know how it works.

**Comment by ysroh** [comment]
And the profile tab shows the correct stereotype because the selected object is the component instance not the definition and it is not possible to change what's under the profile tab. Users can navigate to the definition model in order to see the CCMComponent stereotype under the profile tab.

**Comment by ysroh** [comment]
I would like to definitely hear more about your use case so I can maybe suggest different solutions.

**Comment by j26151** [comment]
I think we are okay with leaving the profile tab alone. The use case here is really trying to keep things clear and simple for our users. As far as they are concerned, a diagram has assemblies, components, ports, connections, and dataspaces. Things like CCMPart can be confusing to them as well as not having a component Icon when they are dealing with components in their diagram. I understand the difference between an instance and a definition, but even then, CCMPart isn't incredibly intuitive regardless. 
Having the label aligned at the top of the component is useful for us from a stylistic perspective. We have components with many ports on them and it is nice to have the port labels on the inside of the component. But, with the name taking up the middle, it causes the label to overlap with the component name in a way that our users from ATCD/RSA are not use to.

**Comment by ysroh** [comment]
Thanks for the clarification. I will look into the alignment issue.

**Comment by j26151** [comment]
The alignment looks great. I think we would still want to see a different icon for the component instances themselves if possible. Also, I assume the black boxes around the DDS ports are something specific to your environment and not included in this fix.

**Comment by j26151** [comment]
This looks great on my end, thank you. You can close this issue

**Comment by ysroh** [comment]
Thanks.
