### ISSUE TITLE
EXT: CCM_DDS::Unlimited bound does not apply

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#381]
# **Issue and tracking information**
When setting the bounds of a sequence to  CCM_DDS::Constants::Unlimited nothing happens and the bound's constant remains "null". The following exception is received:
![image](https://user-images.githubusercontent.com/49879646/160839009-323aac41-aa69-4063-b3ed-92d956038493.png)

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
This issue should be fixed now as I've committed a fix for this issue as part of the Issue #368 commit.

**Comment by j26151** [comment]
I have verified this on my end. Thank you
