### ISSUE TITLE
 Cannot create component in new workspace

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#391]
# **Issue and tracking information**
On a newly created workspace we are not able to click "finish" on the create component dialog unless we de-check both "create package/subpackage" checkboxes. This only happens at the moment on the first creation of the worskapce. If we close the workspace and reopen it, it appears to not have the issue. This issue only happens on the 2.1.0 version of CX, however, if you find a fix here that can be applied to the head of the papyrus branch to add more stability/confidence we won't see this in the future, we definitely want it. I believe it has something to do with the ".metadata/.plugins/.com.zeligsoft.comain.omg.ccm.ui/dialog_settings.xml" file that is missing when a workspace is created, and is created when the workspace is closed and then available on subsequent runs of the workspace.  Attached is an error log I captured when debugging the issue:

### Developer's Actual time spent on fix (hours)  

[error.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/8505337/error.txt)

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
@j26151 I will get it fixed asap.

**Comment by ysroh** [comment]
This should be fixed now in the 2.1.1 maintenance branch.

**Comment by ysroh** [comment]
Let me know if I can close this ticket as well. thanks

**Comment by j26151** [comment]
I verified this on our end, you can close it. Thank you

**Comment by ysroh** [comment]
Thanks
