### ISSUE TITLE
Allow Domains in deployment plans to resync with referenced based domain

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#392]
# **Issue and tracking information**
As of now, if one were to add information such as an additional node to a domain, domains in a deployment plan that reference the modified domain will not update to include the additional node. The domain must be brought into the deployment plan and reconfigured. This is inconvenient and time consuming to do when deployment plans contain many domain configurations. It would be convenient for the domains in the deployment plan to update with the new/deleted nodes on a Repair Deployment command

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by j26151** [comment]
We would like this fix added to both the head of papyrus and the streams/2.1.0 branch

**Comment by J17359** [comment]
> We would like this fix added to both the head of papyrus and the streams/2.1.0 branch

`papyrus` and `streams/2.1.x_maintenance` is what we meant.

**Comment by ysroh** [comment]
Will work on this next. Thanks

**Comment by ysroh** [comment]
Fix merged to papyrus branch.

**Comment by j26151** [comment]
I verified this on our end, you can close it. Thank you
