### ISSUE TITLE
Implementation options for components do not show in indirect situations

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#395]
# **Issue and tracking information**
I have attached a reproducer for this problem. The reproducer contains 3 models.

-ClientServer.uml is the base model. It depends on nobody and is slightly modified such that the source client component has two implementations. Additionally, this model has a dynamic pathmap set.

-BasicPubSub.uml references the ClientServer.uml dynamic pathmap and has the source client included in one of its assemblies. Additionally, this model has a dynamic pathmap set.

-PSDDPubSub.uml references the BasicPubSub.
[cx_example.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/8620252/cx_example.zip)
uml dynamic pathmap and in its deployment plan, it is deploying the assembly from BasicPubSub.uml. If you validate this model, it will fail because it doesn't have an implementation selected for the source client component. If you try to type this, the dialog does not show the available implementations. As a workaround you can either include the ClientServer pathmap which will cause the dialog to be populated, or you can go search for it in the second tab of the dialog. 

 

We would like the implementations to be populated without requiring  the developer PSDDPubSub.uml to know anything about ClientServer.uml.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
This should be fixed now.

**Comment by j26151** [comment]
I have verified this fix. Thanks

**Comment by ysroh** [comment]
Thanks
