### ISSUE TITLE
Direct port connections using AMI or CORBA connectors can have spurious CDP connections

### ISSUE THREAD

**Issue by elder4p** [ZeligsoftDev/CX4CBDDS#4]
This was found while test AXCIOMA support, but has since been found in the original ATCD support, too. To reproduce:

1. define a CORBAInterface with at least one method. Set the interface to be declared Asynchronous.
2. define two monolithic components. On each, define a port, setting the port type to the above interface. Set one of the ports to be a 'conjugate'. Mark both parts as 'asynchronous'.
2. In an AXIOMA model, set each port to use the 'AMI4CCM_Connector'.
3. define an assembly. Add both components, and make a connection between the components.
4. create a deployment plan, domain and node. Deploy all of these, plus the assembly in the plan.
5. Generate descriptors for the plan.

In this case, we expect the tool to generate multiple connects:

1. uses-port to client-side-AMI-connector (sendc -> ami_provides)
2. uses-port to client-side-AMI-connector (use port -> sync_provides)
3. client-side-AMI-connector to provides port (ATCD)
4. client-side-AMI-connector to server-side-AMI-connector (AXCIOMA)
5. server-side-AMI-connector to provides-port (AXCIOMA)
 
However, depending on which direction we created the 'connector' line, one my also see:

1. uses-port to provides-port

Similar behaviour is observed in AXCIOMA mode with a synchronous (CORBA4CCM_Connector).

Root cause is that the code generator is dependent on the order of the 'connectorEnds' in the connection.

**Comment by jwillemsen** [comment]
For AXCIOMA I would expect in the second list of expectations:
4. client-side-AMI-connector to server-side-CORBA-connector (AXCIOMA)
5. server-side-CORBA-connector to provides-port (AXCIOMA)

The AMI4CCM connector on the client side should be connected to a CORBA4CCM connector on the server side, AMI4CCM is a pure client side feature.

**Comment by elder4p** [comment]
> For AXCIOMA I would expect in the second list of expectations:
> 4. client-side-AMI-connector to server-side-CORBA-connector (AXCIOMA)
> 5. server-side-CORBA-connector to provides-port (AXCIOMA)
> 
> The AMI4CCM connector on the client side should be connected to a CORBA4CCM connector on the server side, AMI4CCM is a pure client side feature.

@jwillemsen : I have described the situation incorrectly. In an async connection, the tool generates an AMI connector on the client side, and a CORBA connector on the server side. I am in the process of creating an example that demonstrates the implemented behaviour. I'll attach it once I'm done so as to get your feedback.

**Comment by tuhin-github** [comment]
The issue is fixed for both ATCD and AXCIOMA generation.
