### ISSUE TITLE
Tag streams/v2.1.x-maintenance for Zeligsoft CX 2.1.1 release and roll branch to 2.1.2

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#419]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**

Our program would like to release with your latest hash from the streams/v2.1.x-maintenance branch. Could you please tag that hash for an officially supported release (2.1.1) and then roll the pom.xml's to 2.1.2 for our next release to target on that 2.1.X baseline?

**Comment by elder4p** [comment]
- [x] Tag v2.1.1 created.
- [x] Release created. [Link](https://github.com/ZeligsoftDev/CX4CBDDS/releases/tag/v2.1.1)
- [ ] Pull Request updating to 2.1.2 (pending)

**Comment by J17359** [comment]
Thanks for the super quick turnaround @elder4p !

**Comment by J17359** [comment]
@elder4p were the two issues under "What's Changed" on that release page just the big ticket items? The "Full Changelog" shows more than those two issues in the commit history. Should all those be listed under "What's Changed"?

**Comment by elder4p** [comment]
> @elder4p were the two issues under "What's Changed" on that release page just the big ticket items? The "Full Changelog" shows more than those two issues in the commit history. Should all those be listed under "What's Changed"?

@J17359 : You're right. Github offered the What's Changed list. I removed one issue from it (bumping the version numbers), but I did not look at the full change log. Clearly, the automated process didn't do what I expected. I'll go through the full change log manually, and pull out the issues that look like they are pertinent.

**Comment by elder4p** [comment]
@J17359 : Updated the list to link to all tickets resolved in the release. This is still different from the full change log, as it shows all commits, pull request merges, etc. Not quite the same thing.

Let me know if this is OK.

(I still don't know why the 'generated' release notes where so sparse. Lesson learned: don't count on it working.)

**Comment by J17359** [comment]
> @J17359 : [Updated the list](https://github.com/ZeligsoftDev/CX4CBDDS/releases/tag/v2.1.1) to link to all tickets resolved in the release. This is still different from the full change log, as it shows all commits, pull request merges, etc. Not quite the same thing.
> 
> Let me know if this is OK.
> 
> (I still don't know why the 'generated' release notes where so sparse. Lesson learned: don't count on it working.)

Yeah I think that looks a lot better. I didn't expect the commits, PR merges, etc. to be in the list, only the ticket IDs which it looks like you got now. Thanks @elder4p ! Very weird that the autogenerated version didn't work, I agree.

**Comment by ysroh** [comment]
Can we close this ticket?

**Comment by J17359** [comment]
> Can we close this ticket?

I think we're still waiting on the PR to be merged: https://github.com/ZeligsoftDev/CX4CBDDS/pull/420

**Comment by elder4p** [comment]
Fixed by #420
