### ISSUE TITLE
Change modeling tool to only allow plain text when copying into documentation fields

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#425]
# **Issue and tracking information**
It's very common to copy and paste documentation worked in a confluence(Wiki website that NGC uses) page.  This introduces significant invisible whitespace changes that are a lot of work to change.  Best way to fix it is modifying the XML of the model itself.  Update the modeling tool to only allow plain text when copying and pasting into documentation fields.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
@j26151 Looks like you can paste the text only if you select the "Source" button before pasting it. Can this be a workaround?

**Comment by j26151** [comment]
I think this works as a work around. Is there any way to configure the panel to be "Source" by default?

**Comment by ysroh** [comment]
Unfortunately, that is not possible if the rich text editor is enabled. We enabled the rich text editor for Issue #252 but turning it off would be going back to the text-only comments editor.

**Comment by j26151** [comment]
Okay, we will talk a bit on our side to see what we want to do. Thank you for your response

**Comment by ysroh** [comment]
I didn't notice this in Windows but was able to reproduce it in Linux. I will enable the text editor and test it.

**Comment by ysroh** [comment]
Raised the following bug report to Papyrus: https://bugs.eclipse.org/bugs/show_bug.cgi?id=580867

**Comment by ysroh** [comment]
Sounds good. I am making that change now.

**Comment by j26151** [comment]
Could we have the tag for v2.2.0 updated to include this fix? @J17359

**Comment by ysroh** [comment]
Yes. I will be doing that.

**Comment by ysroh** [comment]
verified.
