### ISSUE TITLE
Any model with Dynamic Pathmap set becomes read-only after generating IDL or descriptors

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#430]
# **Issue and tracking information**
This only occurs in the streams/v2.1.x-maintenance version of CX.

When generating IDL or descriptors on an open model that has a dynamic pathmap, the model becomes read-only immediately after the operation finishes. The only work around is to close and reopen the model each time and try to save all "generations" until you are done making all changes with the model.

To recreate, take any SNA example model like BasicPubSub and add a dynamic pathmap. Save the model. Then generate IDL. Afterwards, expand random packages and you will see they are grayed out. Additionally, trying to change the name of any package like "ports" or "components" will result in the operation being rolled back because the model is read only.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
@j26151 Would you be able to verify this fix on your side? https://github.com/ZeligsoftDev/CX4CBDDS/pull/431

**Comment by j26151** [comment]
This looks to have fixed the issue. Thank you!

**Comment by ysroh** [comment]
Closing...
