### ISSUE TITLE
Issue generating IDL on components with attributes

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#432]
# **Issue and tracking information**
After the most recent PR, I am unable to generate IDL on our BPS example. We get the following error:

![image](https://user-images.githubusercontent.com/49879646/191962375-e26e9a73-2e62-4dd6-9505-01f99c53e9b0.png)

A developer of ours noticed that you renamed the referenced "pathnameSlot" to "pathnamesSLot" and that maybe your zeligsoft_cx/bundles/com.zeligsoft.domain.ngc.ccm.generator/workflow/ngc_idl.oaw's PostGeneration section needs to be updated.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by j26151** [comment]
@ysroh @eposse I know both of you are busy, but we encountered this bug here that is a blocker for a lot of our development and validation for our upcoming release.

**Comment by ysroh** [comment]
We will fix it asap and let you know.

**Comment by ysroh** [comment]
Code reviewed by Paul and fix merged onto papyrus branch.

**Comment by ysroh** [comment]
Let me know if I can close this ticket. thanks

**Comment by ysroh** [comment]
Sounds good, thanks
