### ISSUE TITLE
Tag for Zeligsoft CX 2.2.0 release and roll papyrus branch to 2.3.0 

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#434]
# **Issue and tracking information**
### Developer's Actual time spent on fix (hours)  
# **Issue reporter to provide a detailed description of the issue in the space below**

Could you please perform the following release steps in addition to any of your own?
1. Tag the latest hash from the `papyrus` branch for the 2.2.0 release
2. Branch off the latest hash from `papyrus` branch to create a new `streams/v2.2.x-maintenance` branch
3. Roll version of `papyrus` branch to 2.3.0
4. Roll version of new `streams/v2.2.x-maintenance` branch to 2.2.1

Thanks! Please let @j26151 or I know if there are any questions/concerns.

**Comment by ysroh** [comment]
Would you be able to test the pre-release of version 2.2.0? We are currently doing some basic testing but would like you to test this draft release to make sure everything looks good before making it official.


https://github.com/ZeligsoftDev/CX4CBDDS/releases/tag/v2.2.0-RC1

**Comment by J17359** [comment]
> Would you be able to test the pre-release of version 2.2.0? We are currently doing some basic testing but would like you to test this draft release to make sure everything looks good before making it official.
> 
> https://github.com/ZeligsoftDev/CX4CBDDS/releases/tag/v2.2.0-RC1

I'm building the RPM internally and then will have @j26151 perform a sanity check on it when he gets online. Will post back here afterwards!

**Comment by j26151** [comment]
I just briefly tested generated descriptors and IDL on a more complicated model of ours without seeing any issues. I also tested the new text editor change (removing RTF as default) and that worked as well.

**Comment by J17359** [comment]
@ysroh is there anything else you need us to verify before making the official tag?

**Comment by ysroh** [comment]
Thanks for verifying the build. We will create an official v2.2.0 tag today and let you know.

**Comment by J17359** [comment]
I see the new tag now. Let me know once you've rolled the `papyrus` branch to the new version so we can ensure our latest 2.2.0 version matches your latest hash internally. Thanks again!

**Comment by elder4p** [comment]
@J17359 : pull requests for a version bumped 2.3.0 papyrus branch and 2.2.1 v2.2.x-maintenance branch are above. The attached build artifacts should all be correctly versions. Have a quick look yourself to confirm and let me know.

**Comment by J17359** [comment]
@elder4p PRs look good to me! Thanks for the quick turnaround on this one!

**Comment by J17359** [comment]
@elder4p - actually, look at the 2.2.X PR for me. It might be missing changes in 2 files...

**Comment by elder4p** [comment]
> @elder4p - actually, look at the 2.2.X PR for me. It might be missing changes in 2 files...

@J17359 : Good catch. Missed two files related to the v4.4.0 patch. Technically, not used any more, but if it's in the repo, it should build. Update coming shortly.

**Comment by J17359** [comment]
@elder4p - Looks good now!

**Comment by elder4p** [comment]
PRs #436 and #437 have been merged. Closing.
