### ISSUE TITLE
Tag for Zeligsoft CX 2.3.0 release and roll papyrus branch to 2.4.0

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#439]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

Could you please perform the following release steps in addition to any of your own?

Tag the latest hash from the papyrus branch for the 2.3.0 release
Branch off the latest hash from papyrus branch to create a new streams/v2.3.x-maintenance branch
Roll version of papyrus branch to 2.4.0
Roll version of new streams/v2.3.x-maintenance branch to 2.3.1
Thanks! Please let @J17359 or I know if there are any questions/concerns.

**Comment by elder4p** [comment]
Release steps:

- [x] Create [Release 2.3.0](https://github.com/ZeligsoftDev/CX4CBDDS/releases/tag/v2.3.0)
- [ ] Create maintenance branch off of v2.3.0 tag
- [ ] Version bump to 2.4.0 on papyrus branch
- [ ] Version bump to 2.3.1 on maintenance branch

**Comment by elder4p** [comment]
Refreshed pull requests #440 and #441 so that they include modifications for the same files.

One remaining issue. The v2.3.0 release does not include release artifacts. I suspect this is a problem in the GitHub action. Investigating.

**Comment by elder4p** [comment]
Pushed further changes to #440 and #441 to trigger GitHub release actions when a release is 'published' rather than 'created'. Not sure if this will retrospectively affect v2.3.0 release, but at least corrects things going forward.

**Comment by elder4p** [comment]
Re-created [Release 2.3.0](https://github.com/ZeligsoftDev/CX4CBDDS/releases/tag/v2.3.0) from existing tag, it now has all release artifacts attached.

**Comment by elder4p** [comment]
@j26151 : Do you want to have a look at the release artifacts and pull requests before I merge and close this?

**Comment by j26151** [comment]
Yes, we'd like to do a few quick smoke tests on the release first

**Comment by j26151** [comment]
Everything looked good on my end

**Comment by elder4p** [comment]
Completed. All pull requests merged and release has been published.
