### ISSUE TITLE
A Test ticket

### ISSUE THREAD

**Issue by elder4p** [ZeligsoftDev/CX4CBDDS#44]
[comment]: <> (Two fields below to be filled by ## Developer)
#### Time Tracking

Developer's time Estimated effort to fix (hours): 4.0
Developer's Actual time spent on fix (hours): 3.0

---
#### Description
[comment]: <> (Put ticket description below this line)
This is a test ticket. It will be removed.

**Comment by elder4p** [comment]
@J17359 : Just playing with @CharlesAtZelig. What do you think of the presentation of the following example ticket? If you like it, we'll adjust the template accordingly.

**Comment by elder4p** [comment]
@J17359 : BTW, you can see the editing experience by clicking the three dots, and then *Edit*. We can add such formatting to any existing ticket merely by copying and pasting.

**Comment by J17359** [comment]
> @J17359 : Just playing with @CharlesAtZelig. What do you think of the presentation of the following example ticket? If you like it, we'll adjust the template accordingly.

I like it! That template works for me.

**Comment by elder4p** [comment]
> > @J17359 : Just playing with @CharlesAtZelig. What do you think of the presentation of the following example ticket? If you like it, we'll adjust the template accordingly.
> 
> I like it! That template works for me.

@CharlesAtZelig : Looks like we can use the above as a revised template.

**Comment by CharlesAtZelig** [comment]
User approved and liked - closing

**Comment by CharlesAtZelig** [comment]
User approved and liked - closing
