### ISSUE TITLE
Tag for Zeligsoft CX 2.4.0 release and roll papyrus branch to 2.5.0

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#447]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

Could you please perform the following release steps in addition to any of your own?

Tag the latest hash from the papyrus branch for the 2.4.0 release
Branch off the latest hash from papyrus branch to create a new streams/v2.4.x-maintenance branch
Roll version of papyrus branch to 2.5.0
Roll version of new streams/v2.4.x-maintenance branch to 2.4.1
Thanks! Please let @J17359 or I know if there are any questions/concerns.

**Comment by eposse** [comment]
Release steps:

- [x] Create [Release 2.4.0](https://github.com/ZeligsoftDev/CX4CBDDS/releases/tag/v2.4.0)
- [x] Create streams/v2.4.x-maintenance branch off of v2.4.0 tag
- [x] Version bump to 2.5.0 on papyrus branch. See #449
- [x] Version bump to 2.4.1 on streams/v2.4.x-maintenance branch. See #448

**Comment by eposse** [comment]
Completed. All pull requests merged and release has been published.
