### ISSUE TITLE
AXCIOMA model progressive deployment additions

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#45]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
In the AXCIOMA model both <implementation> and <instance> definitions should be in the descriptor files for non-local client or server ports that are defined on components, even if they are not connected to anything (like a non-deployed “surrogate” component) in the deployed assembly.  Also, if non-local, then there should also be a reference to the client or server connector component <instance> in the <localityConstraint> container process definition that contains the parent component executor, even if there is no <connection> in the same CDP to connect to it automatically at startup.  This allows for dynamic connectivity later on.

**Comment by tuhin-github** [comment]
Fixed by PR #51

**Comment by j26151** [comment]
I have noticed a few more issues here. The first one being that a progressive connections for a Facet should not have a second connection (The one with the external reference).  External references are only ever available for facets. Second, the name in the external reference for a receptacle is not being populated correctly. It should be the string value used in the "nl.remedy.it.DnCX11.RegisterNaming" property for the component that has the facet that the receptacle is connecting to. I have attached 5 CDP files to help show the difference. The first, ClientServer.cdp.txt, is the example as a whole. The next two, EchoServer_comp.cdp.txt and SourceClient_comp.cdp.txt are the results outputted by CX. Lastly, EchoServer_comp.cdp.working.txt and SourceClient_comp.cdp.working.txt are examples of CDP files allowing progressive deployment to work.
[ClientServer.cdp.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/3939586/ClientServer.cdp.txt)
[EchoServer_comp.cdp.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/3939587/EchoServer_comp.cdp.txt)
[EchoServer_comp.cdp.working.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/3939588/EchoServer_comp.cdp.working.txt)
[SourceClient_comp.cdp.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/3939589/SourceClient_comp.cdp.txt)
[SourceClient_comp.cdp.working.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/3939590/SourceClient_comp.cdp.working.txt)

**Comment by tuhin-github** [comment]
Please attach the model for which the cdp files are being generated. You can put everything in a zip file and upload it here.

**Comment by j26151** [comment]
Attaching zip with the model file. 
[progressive.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/3941174/progressive.zip)

**Comment by tuhin-github** [comment]
> Second, the name in the external reference for a receptacle is not being populated correctly. It should be the string value used in the "nl.remedy.it.DnCX11.RegisterNaming" property for the component that has the facet that the receptacle is connecting to.

Components in the attached model do not have any value for the "nl.remedy.it.DnCX11.RegisterNaming" property. But, in your “SourceClient_comp.cdp.working.txt” file, _location_ for the external reference has the following value (this seems incorrect following the requirement mentioned above):

<location>corbaname:rir:/NameService#echoServer_comp_echoConnectFacet</location>


Whereas the “SourceClient_comp.cdp.txt” has the following value (which seems correct following the requirement mentioned above as the ‘RegisterNaming’ property value is empty)

<location>corbaname:rir:/NameService#echoServer_comp</location>


Could you please confirm if the latter one is actually the working version?

**Comment by j26151** [comment]
Sorry, The only  DnCX11.RegisterNaming value in the EchoServer_comp file (echoServer_comp_echoConnectFacet) is the one that we need the location value to point to in the SourceClient_comp file: <location>corbaname:rir:/NameService#echoServer_comp_echoConnectFacet</location>

This is how the middleware knows how to find the Component/entity that provides the facet that the connection is looking for. 

Since the entity "ClientServer_asm.echoServer_comp.echoConnectFacet"  is the entity that has the facet that we are trying to connect to, we need to use the RegisterNaming that is associated with it

**Comment by tuhin-github** [comment]
Thank you for the clarification. PR #62 is created for addressing the issues.
