### ISSUE TITLE
AXCIOMA Connector Inheritance Issues

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#48]
# **Issue and tracking information**
There appears to be an issue with generating taginfo and descriptor files from the model when that model is using a connector library model that extends another connector library model (which in turn extends DDS4CCM) 

### Developer's Actual time spent on fix (hours) : 11 

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by elder4p** [comment]
We’ve back-ported your model to ATCD and ran it on 1.5.14, and see exactly the same names as you are seeing in AXCIOMA. *Hence, this is not a regression from ATCD support.*

This indicates we are seeing an ATCD/AXCIOMA difference (in the IDL compiler output?), and that we must adjust the generation of the descriptor files accordingly.

We will need to determine exact specifications, but have already determined where these names are being created. So, once rules are settled upon, it should be a quick to update the descriptor generators.

**Comment by tuhin-github** [comment]
For future reference, the portnames for pub-sub connections are being generated in the method named "createEndPoint". The sequence of intermediate methods that need to be visited for reaching the "createEndPoint" method from the "mainTransform" method in both axcioma and atcd generation is listed below. 

**FORMAT:** Line (line number in axcioma-generation-file, line number in atcd-generation-file)

1. Line(53, 50): let connectors = deployment.part.modelElement.typeSelect(DataSpace)

2. Line(64, 59): connectors.createInstances(this, deployment)

3. Line(338, 343 ): Void createInstances(DataSpace dataSpace, DeploymentPlan plan, CCM::CCM_Deployment::DeploymentPlan deployment)

4. Line(341, 346): Void visit(DataSpace dataSpace, DeploymentPlan plan, CCM::CCM_Deployment::DeploymentPlan deployment, AssemblyImplementation assembly )

5. Line(344, 349): Void visit(CCMConnector connector, DataSpace dataSpace, DeploymentPlan plan, CCM::CCM_Deployment::DeploymentPlan deployment, Object expansionObject)

6. Line(347, 352): Void visit(CCMConnector connector, DataSpace dataSpace, DeploymentPlan plan, CCM::CCM_Deployment::DeploymentPlan deployment, Object expansionObject, CCMConnector origConn)

7. Line(378, 383): Void createDDS4CCMConnectorFragmentHelper(DeploymentPart source, DeploymentPart target, DeploymentPlan plan, CCM::CCM_Deployment::DeploymentPlan deployment, DataSpace dataSpace, InterfacePort sourcePort, CCMConnector origConn )

8. Line(516, 521): Void createConnectionsForDDS4CCMConnectorFragment(DeploymentPlan plan, InterfacePort sourcePort, InstanceDeploymentDescription compInstance, InstanceDeploymentDescription fragmentInstance, DataSpace dataSpace, ExtendedPortType porttype, CCMConnector origConn)


9. Line(551, 559): create PlanConnectionDescription createDDS4CCMConnection(NamedElement dep, InterfacePort sourcePort, InstanceDeploymentDescription compInstance, InstanceDeploymentDescription fragmentInstance, DataSpace dataSpace, String prefix )


10. Line(835, 708): create PlanSubcomponentPortEndpoint createEndPoint(PlanConnectionDescription conn, Boolean provides, Boolean multiple, String portName, InstanceDeploymentDescription instance )

**Comment by elder4p** [comment]
@j26151 , @J17359 : We are blocked until you give us specifications on what the proper names should be in the CDP and taginfo files. As stated earlier, there have been no changes to ATCD descriptor generation. AXCIOMA does exactly the same thing, as we have no specification to do otherwise.

**Comment by j26151** [comment]
@elder4p It looks as if there was an issue with the way our "SPDM" model included the "PSAT" model. As in the PSAT Model update wasn't passed to SPDM. I will look more into this. This would explain the CDP issue, however, I havn't been able to see what the .taginfo difference is caused by. I will update this once I know more.

**Comment by j26151** [comment]
This issue can be closed. There is no issues with connector inheritance. It was an issue on our end not updating module instantiations.

**Comment by elder4p** [comment]
Closing, per @j26151 last comment
