### ISSUE TITLE
Tag for Zeligsoft CX 2.5.0 release and roll papyrus branch to 2.6.0

### ISSUE THREAD

**Issue by tcalder1** [ZeligsoftDev/CX4CBDDS#481]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
Could you please perform the following release steps in addition to any of your own?

- Tag the latest hash from the papyrus branch for the 2.5.0 release
- Branch off the latest hash from papyrus branch to create a new streams/v2.5.x-maintenance branch
- Roll version of papyrus branch to 2.6.0
- Roll version of new streams/v2.5.x-maintenance branch to 2.5.1
- Thanks! Please let myself, Michael Steppe or Eric Mammoser know if there are any questions/concerns.

**Comment by eposse** [comment]
Hi. I just want to confirm, this 2.5 release won't include all the work on Issues #471 and #476, as they are not finished, correct?

(Tagging @j26151 and @J17359 for their input).

**Comment by j26151** [comment]
Correct, this release will not contain all of those log4j changes as they are not finished yet and largly untested by our team

**Comment by eposse** [comment]
Great! I'll work on this release now.

**Comment by eposse** [comment]
Release steps:

- [x] Create [Release 2.5.0](https://github.com/ZeligsoftDev/CX4CBDDS/releases/tag/v2.5.0)
- [x] Create streams/v2.5.x-maintenance branch off of v2.5.0 tag
- [x] Version bump to 2.6.0 on papyrus branch. See https://github.com/ZeligsoftDev/CX4CBDDS/pull/483
- [x] Version bump to 2.5.1 on streams/v2.5.x-maintenance branch. See https://github.com/ZeligsoftDev/CX4CBDDS/pull/482

You can get the artifacts in the following links:

- For [2.5.1](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/6789391727?pr=482)
- For [2.6.0](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/6789527283?pr=483)

I've tested both RPM builds on a CentOS 7 VM. Everything looks good.

Let me know if I can merge the two pull requests.

**Comment by eposse** [comment]
Merged as per @J17359 request.

Can I close this one now?

**Comment by J17359** [comment]
> Merged as per @J17359 request.
> 
> Can I close this one now?

I'm cool with closing! Thanks @eposse !
