### ISSUE TITLE
Local Interface Constraint throws errors with multiple multi node deployments

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#49]
# **Issue and tracking information**
If an application has an assembly that contains two components connected with a local client server connection and that assembly is replicated for deployment (i.e. multiple of these assemblies spread out across nodes to provide a map-reduce operation) The deployment plan will complain that the extra assembly facets are not local to the original receptacle. This was reproduced using our SignalProcessingDataModel.emx file which should be similar to the one here: https://github.com/ZeligsoftDev/CX4CBDDS/blob/master/examples/SNA_Examples/SignalProcessingDataModel_asm/Deployment/descriptors/SignalProcessingDataModel_asm.emx

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by elder4p** [comment]
Fixed by pull request #52.
