### ISSUE TITLE
Change IDL generation to remove "//@top-level" and use "@nested

### ISSUE THREAD

**Issue by emammoser** [ZeligsoftDev/CX4CBDDS#493]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

For our generated IDL structure and messages, we have "//@top-level true/false" appended to every definition. While this is valid RTI DDS syntax, it is not valid for all DDS vendors or IDL in general. Instead, we would like this changed to be the equivalent @nested prepended to the structure definition in a similar fashion to the @final/@appendable values (i.e. no prefixed comments). The values also become the opposite. So:

"//@top-level true" becomes "@nested(FALSE)" and
"//@top-level false" becomes "@nested(TRUE)"

We want this change made to the following branches:
1. streams/v2
2. streams/v3

**Comment by jwillemsen** [comment]
This issue is related with https://github.com/RemedyIT/ciaox11/pull/428, AXCIOMA is moving from `@Toplevel`/`@top-level` to `@nested` which is part of [IDL 4.2](https://www.omg.org/spec/IDL/4.2).

**Comment by eposse** [comment]
A couple of questions.

1. If I understand correctly, the following, current pattern:
```idl
    @final
    struct TestData_msg {
        // ...
    }; //@top-level true
```
should become
```idl
    @final
    @nested(TRUE)
    struct TestData_msg {
        // ...
    }; 
```
Is this correct?

2. Assuming that it is correct, does the order of the annotations (@final/@appendable/@nested) matter?
3. Do we have to remove the "//@top-level true" comment?

**Comment by jwillemsen** [comment]
1. nested is the inverse of top-level, so it should become

```idl
    @final
    @nested(FALSE)
    struct TestData_msg {
        // ...
    }; 
```

2. The order of the annotations doesn't matter, IDL4 defines a lot more possible annotations
3. Yes, `//@top-level true` should be removed, it is a RTI specific annotation for which we had a hack in AXCIOMA which was causing problems when working on more IDL4 annotation support

**Comment by emammoser** [comment]
@eposse I agree with Johnny above. Let me know if you have any other questions

**Comment by eposse** [comment]
Two more questions: 

1. `@nested(TRUE)` is the default, correct?
2. if the answer is yes, is it still required to add `@nested(TRUE)` or is `@nested(FALSE)` the only one required (if the struct or message is top-level)?

**Comment by emammoser** [comment]
> @nested(TRUE) is the default, correct?
if the answer is yes, is it still required to add @nested(TRUE) or is @nested(FALSE) the only one required (if the struct or message is top-level)?

I am not sure what you mean by default. We don't have any selectable options for "top-level" at the moment, so I wouldn't expect there to be any for "nested" now. As far as I know, if we have a struct (CXStruct), it should be @nested(TRUE) and if we have a message (DDSMessage) it should be @nested(FALSE)

**Comment by eposse** [comment]
By default I meant that any declared CXStruct or DDSMessage was "nested", but your answer clarifies that CXStructs are nested and DDSMessages are not.

But the second question is still relevant. While it is clear that a DDSMessage must have the `@nested(FALSE)` annotation, should every CXStruct have an explicit `@nested(TRUE)` annotation?

**Comment by emammoser** [comment]
Yes, I believe that is how it works currently with top-level, right? At least looking through generated IDL that we have, that is the case.

**Comment by eposse** [comment]
I've tested the solution and prepared the builds for you to test:

* [build for streams/v2](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/7980526811)
* [build for streams/v3](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/7979215397)

Let me know if you have any issues.

**Comment by eposse** [comment]
Here are the updated builds:

* [build for streams/v2](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/7993644542)
* [build for streams/v3](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/7993770282)

Let me know if you have any further comments.

**Comment by eposse** [comment]
And the latest updated build:

* [build for streams/v2](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/7994246717)
* [build for streams/v3](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/7994185154)

**Comment by eposse** [comment]
By the way, should I add these changes to the streams/v2.5.x-maintenance branch too?

**Comment by emammoser** [comment]
No, that streams maintenance branch is meant to work with a specific version of AXCIOMA (which maybe we should document in CX? Not sure) and that version of AXCIOMA does not use @nested, it only uses the top-level annotation

**Comment by eposse** [comment]
Ok. Let me know when you have tested to merge it. Thanks.

**Comment by emammoser** [comment]
I have tested the v2 stream and it worked as expected. So I think you can merge them.

**Comment by eposse** [comment]
Closing
