### ISSUE TITLE
Same name used for multiple instances/connections with AMI4CCM

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#50]
# **Issue and tracking information**
When attempting to do an AMI4CCM project with 1 client connected to 3 server components, it was noticed that the CDP generated is incorrect. 3 AMI4CCM instances are created in the locality constraint for the 1 client (1 for each connection to a server), and all 3 of these instances have the same name which we believe need to be different. Additionally, the connection names are also repeated. See attached CDP file (I had to link as ".txt" for github to let me insert it)
[AMI4CCM.txt](https://github.com/ZeligsoftDev/CX4CBDDS/files/3768520/AMI4CCM.txt)

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by j26151** [comment]
The model you could use to recreate this CDP file (after migrating to axcioma) is at: https://github.com/ZeligsoftDev/CX4CBDDS/blob/master/examples/SNA_Examples/AMI4CCM_asm/Deployment/descriptors/AMI4CCM_asm.emx

**Comment by MHayman5** [comment]
Note that this issue violates a fundamental D&C *.cdp deployment descriptor file rule that all `<name>` tags in the same CDP file must be unique.  This applies both `<instance>` and `<connection>` entries for this particular AMI4CCM use case.

**Comment by simonredding1** [comment]
This problem (#50) will be addressed in the next drop along with ticket #45. We had planned to deliver that drop at the end of this week (Oct 24th) but due to some difficulties, that must be delayed until mid next week.

**Comment by elder4p** [comment]
@tuhin-github : Can you take a look at this one next.

**Comment by tuhin-github** [comment]
@elder4p This is fixed by PR#51 (https://github.com/ZeligsoftDev/CX4CBDDS/pull/51) and has been tested for the use-case mentioned above. So, I am closing the issue. Please reopen if a similar problem is found for some other use-cases.

**Comment by j26151** [comment]
I believe this ticket should be reopened.  The first issue that I have noticed is in order to connect a facet to a receptacle, they both must be the same type, either CORBA or AMI4CCM. This should not be the case. The Server side facet should always be CORBA. The client side should be able to be either CORBA or AMI4CCM. This allows the client to either be synchronous only(CORBA), or both asychronous/synchronous(AMI4CCM).

**Comment by elder4p** [comment]
Re-opening issue, per [comment](https://github.com/ZeligsoftDev/CX4CBDDS/issues/50#issuecomment-561809892) by @j26151.

**Comment by j26151** [comment]
When attempting to generate descriptors for any of our AXCIOMA models, I get an error 

> !MESSAGE Failed executing the workflow workflow/ngcgeneratorNoPostGeneration.mwe on platform:/resource/BasicPubSub/ModelFiles/BasicPubSub.emx
SEVERE: Error in Component generator of type com.zeligsoft.base.zdl.oqw.ZExtendGenerator:
       "EvaluationException : no viable alternative at input ';' on line 271
       template::mainTransformDispatcher.ext[1081,25] on line 32 'deployment.getModelType()'  
       nofile[0,32] on line 1 '.mainTransformDispatcher(element)'
