### ISSUE TITLE
Add optional ZMQ Connector (PSDD4CCM) properties

### ISSUE THREAD

**Issue by emammoser** [ZeligsoftDev/CX4CBDDS#518]
# **Issue and tracking information**
We have recently begun using the PSDD4CCM connector in our projects and noticed that we needed more ability to configure the connector. CIAOX11 has the following documentation for all of its properties here: https://github.com/RemedyIT/ciaox11/blob/master/connectors/psdd4ccm/docs/src/psdd4ccm_zmq_details.adoc

We would like all of the properties mentioned in this deployment section available to us in the deployment plan configuration panel so that we can set these values if and when we need them. They should all default to not generating options if nothing is set.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by emammoser** [comment]
We would like this change placed on all of our current streams. 2.X, 3.X, and the maintenance stream 2.5.X

**Comment by eposse** [comment]
@emammoser I have a build based on v2 [here](https://github.com/ZeligsoftDev/CX4CBDDS/actions/runs/12130056479) for you to test. Note that, according to the docs, the "service" properties are specified in the Container Processes, rather than the connectors or ports.

Let me know if it works for you.

Also, will you be needing migration to add these properties in older models?

**Comment by emammoser** [comment]
@eposse  Did you add all of the other ZMQ properties? Not just the service ones?

**Comment by eposse** [comment]
Yes, I've added all, the publisher, subscriber and serialization properties, which are editable in the connectors and ports themselves.

**Comment by emammoser** [comment]
Great, I will hopefully have some time this week to give it a try. Thank you

**Comment by emammoser** [comment]
I tested this and everything looked good on my end. We don't need a migration. The connector properties load into previous deployment plans. The container processes would need to be re-created to get the new ZMQ properties, but I don't think that is a concern for us. 

Can we get this update on 3,X and 2.5.X? Thank you.

**Comment by eposse** [comment]
I've merged it to v2 (aka 2.6), v3 and v2.5.x-maintenance.

Can we close it?

**Comment by emammoser** [comment]
Yes, thank you for the quick turnaround
