### ISSUE TITLE
Add githash to RPM release field

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#54]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
Today, the CX RPMs that are generated simply have a release field of "0.timestamp" (see https://github.com/ZeligsoftDev/CX4CBDDS/blob/master/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L9 and https://github.com/ZeligsoftDev/CX4CBDDS/blob/master/releng/com.zeligsoft.dds4ccm.update.atcd/rpm_build/zeligsoftCX_atcd.spec#L9). While this is nice, it would be better to also include a git hash of the CX repo where the RPM was generated so we can better see differences between RPM versions. The git hash should go after the timestamp so that yum can still use the timestamp to decide which RPM is newer than another (and because git hashes are not incremental). 

An alternative solution would be to parameterize the release field string so that anyone building the RPM could inject their own release information (but still default to the timestamp). Something like this:
```
%define ifdef()      %if %{expand:%%{?%{1}:1}%%{!?%{1}:0}}
%define defaultRel   0.%(date "+%y%m%d%H%M")

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Parse arguments
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Set the release of the RPM according to the value of the 'trueRel' input
# variable, or use a string constant
%ifdef trueRel
   %define rel %{trueRel}
%else
   %define rel %{defaultRel}
%endif

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Define packages
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Name:          cx-atcd
Version:       %{ver}
Release:       %{rel}
```

**Comment by elder4p** [comment]
@tuhin-github : This one is less important than the other 1.6.1 tickets, but worth doing once we have the time.
