### ISSUE TITLE
Generation of spurious connections for model with nested assemblies having unconnected ports

### ISSUE THREAD

**Issue by tuhin-github** [ZeligsoftDev/CX4CBDDS#6]
# Time Tracking  information

# Estimate of time to fix :  

# Actual time spent on fix:   

This issue is related to the issue #5. 

This was found while testing AXCIOMA support, but has since been found in the original ATCD support, too. To reproduce (in ATCD support):

	1.	Define a CORBAInterface. Set the interface to be declared Asynchronous.
	2.	Define two monolithic components: CompA and CompB. On each, define a port (i.e., portA and portB), setting the port type to the above interface. Set the port in CompA to be a 'conjugate'. Mark both ports as 'asynchronous'.
	3.	Define two assemblies: AssemblyA and AssemblyB. On each, define a port, setting the port type to the above interface. Set the port in AssemblyA to be a 'conjugate'. Mark both ports as 'asynchronous'.
	4.	Add ‘a:CompA’ in AssemblyA and ‘b:CompB’ in AssemblyB. Make delegation connections from the external ports of the assemblies to ‘a:CompA’ and ‘b:CompB’.
	5.	Define another assembly: AssemblyAB. Add ‘assemblyA:AssemblyA’ and ‘assemblyB:AssemblyB’. Make a connection between their ports. 
	6.	Add another instance ‘assemblyA2:AssemblyA’ in the assembly, without making any connections to its port.
	7.	Create a deployment plan, domain, process and node. Deploy all of these.
	8.	Generate descriptors for the plan.

In this case, we expect the tool to generate three connections for 1 physical connection between ‘assemblyA::compA::portA’ and ‘assemblyB::CompB::portB’ in the assembly of the ATCD model:

	1.	uses-port to client-side-AMI-connector (sendc -> ami_provides)
	2.	uses-port to client-side-AMI-connector (use port -> sync_provides)
	3.	client-side-AMI-connector to provides port

However, in the current support, the tool generates 3 more connections by incorrectly assuming the presence of a physical connection between ‘assemblyA2::compA::portA’ and ‘assemblyB::CompB::portB’.

Root cause is that, while finding ‘deploymentPart’ for a receptPart, the code generator searched for the deploymentParts whose ‘modelElement’ matches  the receptPart. As deploymentParts related to different deployed instances of an AssemblyImplementation can have identical modelElements, this approach of finding deploymentPart is problematic.

Find the attached example where we expect 3 connections to be generated, but the tool generates 6 connections.

[NestedAssemblyWithSpuriousConn.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/3122185/NestedAssemblyWithSpuriousConn.zip)

**Comment by elder4p** [comment]
@tuhin-github: This ticket references #5, which appears to be an identically named ticket, that is now closed. Is there were remaining on this ticket that was not included in the fix for #5?

**Comment by tuhin-github** [comment]
@elder4p: Fix provided for #5 did not take care of the issue mentioned in this ticket. 
This ticket is similar to #5 considering the nature of the problem; but the context of their occurrence is completely different. While #5 occurs in cases where we have an unconnected instance of a monolithic component in an assembly implementation, this ticket mentions about a scenario where we have an unconnected instance of an assembly implementation inside an assembly having nested assemblies.

**Comment by CharlesAtZelig** [comment]
Added time tracking fields on 2019-09-30 @ 14:22

**Comment by elder4p** [comment]
Fixed by pull #53 .
