### ISSUE TITLE
GIS Templated Connectors cannot be typed with a Struct, only DDS message

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#63]
# **Issue and tracking information**
If a GIS Templated connector is typed with something other than the DDS message, than the IDL created for the templated connector will not contain the IDL include for the struct.

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**

**Comment by ysroh** [comment]
@j26151 Can you please provide a simple model with connector type using CXStruct instead of DDSMessage and provide me with the expected IDL?

**Comment by ysroh** [comment]
Would it be sufficient to generate CXStruct on a separate file on its own and add include statement in the generated connector type IDL?

**Comment by j26151** [comment]
[ioconnector_struct.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/5835816/ioconnector_struct.zip)
I've attached a project with a model (and generated files). In this model, in the ports directory, there is a "defn" module with a struct defined. Next to the "defn" module there is a templated GIS connector, that is templated with that struct. In the generated IDL, the connector's IDL file does not have an include to the "defn" idl file where the struct exists. 

I don't know if we want to generate all CXStructs in separate files. That seems like it could bite us in the future where we might have a lot of structs that get used as a templated data type, so they they become forced into their own IDL file.

**Comment by ysroh** [comment]
@j26151 Make sense. I will add include to the IDL file containing the struct.

**Comment by ysroh** [comment]
@j26151 Please let me know if the fix is working. I did test but I cannot generate your model since I don't have the template module.

**Comment by j26151** [comment]
I just tested and it worked as we discussed. Thank you. This ticket can be closed.

**Comment by ysroh** [comment]
Thanks
