### ISSUE TITLE
New monolithic component default implementation name has no "_comp" suffix

### ISSUE THREAD

**Issue by elder4p** [ZeligsoftDev/CX4CBDDS#7]
When you create a new monolithic component in the CX4CBDDS modeling tool, check the Create Implementation option, and select Monolithic as the Kind, the Implementation name has the "_comp" suffix from the Component Name removed. The workaround for this problem is to uncheck the Use default option from the Implementation name setting and add the "_comp" suffix manually. The major inconvenience of this issue is that the error does not appear until much later when attempting to build the generated IDL and the error message that comes out is not very helpful, especially to those unfamiliar with our build system.

Update 1/17/19: Adding a "_comp" suffix is an NGC convention, not anything that should be hard coded into the open standards based open source CX4CBDDS tool. Preferred suffix strings such as this that show up as defaults in the new component creation wizard or implementation should be driven by CX4CBDDS project level preferences/config settings. These in turn should be settable via config file vs. user interaction in our default environment for a new Eclipse workspace, as other defaults for CX4CBDDS already are. 

Update 1/19/19: **Recommended Fix**: The issue here is that CX4CBDDS is automatically stripping the "_comp" suffix off of the monolithic implementation name. So if you name your component "Generic_com", the monolithic implementation will, by default, be named "Generic_com". But the second you type the "p" character, CX4CBDDS changes the default name of the monolithic implementation to "Generic", stripping off the "_comp" suffix. I imagine that this behavior is something that we specifically asked for in the past, but I don't think CX4CBDDS should be doing that because (1) as you said, "_comp" is our convention and CX4CBDDS shouldn't be treating it as a special case and (2) stripping that "_comp" suffix off of the monolithic implementation actually causes the generated IDL file to be misinterpreted by multiple layers of the build system and the Eclipse plug-ins.

**Comment by tuhin-github** [comment]
Fixed with #16
