### ISSUE TITLE
Generate RPM for cx-papyrus that can be installed with no network connectivity

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#75]
# **Issue and tracking information**

### Developer's time Estimated effort to fix (hours):
4
### Developer's Actual time spent on fix (hours)  
8

# **Issue reporter to provide a detailed description of the issue in the space below**
I did a little investigation into packaging CX as an RPM now that you’re using Papyrus instead of RSA. I’ve collected some notes/action items below that I believe need to be addressed before having an RPM that works:
1.	The spec file will need its version updated to 2.0.0 for Papyrus-based CX:  https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L8 
2.	All /opt/IBM/SDP calls in https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L48-L114 will need to be changed to /opt/Papyrus
3.	Two of your installation units seem to have changed names: https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L92-L93 
a.	com.zeligsoft.base.feature.group --> com.zeligsoft.base_feature.feature.group
b.	com.zeligsoft.cx.feature.group --> com.zeligsoft.cx_feature.feature.group
4.	And lastly, the installIUs seem to be requiring dependencies that are not provided by Papyrus (downloaded from https://www.eclipse.org/downloads/download.php?file=/modeling/mdt/papyrus/rcp/2019-06/4.4.0/papyrus-2019-06-4.4.0-linux64.tar.gz) automatically, meaning that they attempt to reach out to the network to get them ([cx_install_error.log](https://github.com/ZeligsoftDev/CX4CBDDS/files/4249832/cx_install_error.log)). Previous CX installations could be installed with no network connectivity at time of install. This needs to be the case in order to install this type of software via RPM.

**Comment by J17359** [comment]
Sorry about the closing and opening of this ticket! I had accidentally clicked submit before giving a description so I closed the ticket then realized I could edit my original (empty) description, so I reopened it after editing.

**Comment by elder4p** [comment]
@J17359 : Commit coming that definitely fixes the RPM version, papyrus location and feature references. I've updated the bundled dependencies so that they install successfully in the following scenario:

- 'Eclipse Modeling Tools, 2019-06 as the base installation
- Papyrus for UML, 2019-05 (4.4.0) installed into that (from the [2019-06 update site](http://download.eclipse.org/releases/2019-06/201906191000)
- Install CX from there. (Check with no internet connection.)

**Comment by J17359** [comment]
@elder4p you need to update the executable name in /opt/Papyrus to "papyrus" instead of "eclipse":
https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L53
https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L68
https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L87
https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L100

**Comment by J17359** [comment]
[cxInstallError.log](https://github.com/ZeligsoftDev/CX4CBDDS/files/4268835/cxInstallError.log)

"Hacked" my way through the install (symlinked /opt/Papyrus/eclipse to /opt/Papyrus/papyrus) and found something else. See the above error log. Looks like your RPM install needs to also contain the xtend dependencies included in your zip?

**Comment by J17359** [comment]
It might be helpful to have your automated tests run installs of the RPMs generated by the rpmbuild job. That way we can hopefully catch some of these spec file issues earlier.

FYI, our Eclipse environment looks like the following:
Papyrus from the link you sent back in January: https://www.eclipse.org/downloads/download.php?file=/modeling/mdt/papyrus/rcp/2019-06/4.4.0/papyrus-2019-06-4.4.0-linux64.tar.gz

Is that Papyrus tarball equivalent to what you mentioned below?
> * 'Eclipse Modeling Tools, 2019-06 as the base installation
> * Papyrus for UML, 2019-05 (4.4.0) installed into that (from the [2019-06 update site](http://download.eclipse.org/releases/2019-06/201906191000)
> * Install CX from there. (Check with no internet connection.)

**Comment by elder4p** [comment]
@J17359 : Thanks. I will correct this on Monday. For the record:

- missing bundle is: org.eclipse.xtext.xbase

I will test with Papyrus RCP

**Comment by elder4p** [comment]
@J17359 : merged a fix that:
- includes org.eclipse.xtext.xbase feature in the update sites.
- refers to the install papyrus as /opt/Papyrus/papyrus

I have tested, but my Linux test machine is not a native RPM platform, so I distrust it. Can you confirm this works for you.

**Comment by J17359** [comment]
> I have tested, but my Linux test machine is not a native RPM platform, so I distrust it. Can you confirm this works for you.

Building your software now. Should have feedback in an hour.

**Comment by J17359** [comment]
That looks to have fixed it! I installed Papyrus RCP (2019-06) from tarball I linked [here](https://github.com/ZeligsoftDev/CX4CBDDS/issues/75#issuecomment-592704417). Then I built and installed your CX RPM successfully.

I have just one small request left (and you may decide this is something we need to configure on our end). The [axcioma spec file ](https://github.com/ZeligsoftDev/CX4CBDDS/blob/papyrus/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L92-L96) today only installs the five Zeligsoft feature groups. Papyrus RCP doesn't come with any Eclipse CDT support so we've been installing the full CDT feature from your p2 site. Your Zeligsoft plugins all install successfully pulling in some of the CDT plugins already (org.eclipse.cdt.<codan.core, core, core.native, make.core, and managedbuilder_core>). Our plugins we build against your software requires a bit more from CDT and by installing the full CDT suite from your p2 site (manually), we can build our software successfully. 

Would you be willing to install all of the CDT installation units along with your Zeligsoft installation units via the spec file/RPM? Maybe there could be a blurb in the %description field of the spec file stating that the RPM should only be installed into Papyrus RCP. If there are use cases in the future installing into different Eclipse environments, we could work together to set that up with spec files as well.

**Comment by elder4p** [comment]
@J17359 : installing the CDT as part of the RPM seems reasonable to me. We produce it to meet your needs anyhow. I'll try to get to it tomorrow.

**Comment by elder4p** [comment]
Pull request #78 resolves the last remaining issue. Closing.
