### ISSUE TITLE
Validation errors found in deployment plans should identify which deployment plan the validation error is found in

### ISSUE THREAD

**Issue by elder4p** [ZeligsoftDev/CX4CBDDS#8]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours) - since the issue is reopened on September 03, 2019 : 36.5   

# **Issue reporter to provide a detailed description of the issue in the space below**

Validation errors found in deployment plans should identify which deployment plan the validation error is found in. Many of our models contain numerous deployment plans, some of which are quite similar and use common assemblies. Finding which plan is the source of a validation error can be a very time consuming process. For instance, the following validation error messages do not specify which deployment plan is the source: 

There were problems in executing the transformation: NLS missing message: GenerateAllDescriptors_FailureExecutingWorkflow in: com.zeligsoft.domain.ngc.ccm.descriptorgeneration.l10.Messagesworkflow/ngcgeneratorNoPostGeneration.mwe on platform:/resource/XYZ/ModelFiles/XYZ_Assemblies.emx. Connection between deployment parts testDriver_comp::idleGenerationClient and idleGenerator_comp_2::idleGenerationFacet on local interface requires collocation.

**Comment by elder4p** [comment]
Analysis: The message being issued is part of the code generation templates. Apart from it providing too little information, CX provides a better validation framework than the one used here. The following fixes are proposed:

- Include more information in the current message. In particular, add references to the deployment plan.
- fix the "NLS missing message". While not critical to function, it is the manifestation of a typographical error
- (more involved fix). Write a CX validation rule to detect the issue as part of the **Validate** action. This will have the side effect of highlighting the problematic elements in model tree, and displaying them in the Problems view. This is substantially better than the current behaviour, where the message is displayed in a pop-up dialog, and hidden away in the Eclipse error log.

**Comment by J17359** [comment]
> 
> 
> Analysis: The message being issued is part of the code generation templates. Apart from it providing too little information, CX provides a better validation framework than the one used here. The following fixes are proposed:
> 
>     * Include more information in the current message. In particular, add references to the deployment plan.
> 
>     * fix the "NLS missing message". While not critical to function, it is the manifestation of a typographical error
> 
>     * (more involved fix). Write a CX validation rule to detect the issue as part of the **Validate** action. This will have the side effect of highlighting the problematic elements in model tree, and displaying them in the Problems view. This is substantially better than the current behaviour, where the message is displayed in a pop-up dialog, and hidden away in the Eclipse error log.

SNA votes for the "more involved fix"

**Comment by J17359** [comment]
@elder4p - In regards to our phone discussion today, I believe this is the only additional GitHub issue (not counting https://github.com/ZeligsoftDev/CX4CBDDS/issues/23) that we'd like to have in the final CX 1.6.0.

**Comment by elder4p** [comment]
Resolved via #19.

**Comment by J17359** [comment]
Just want to elevate Eric's comment above in case it was missed...

**Comment by elder4p** [comment]
Re-opening Issue.

**Comment by tuhin-github** [comment]
> I attempted to test this fix on our end and I didn't notice a difference in behavior. I created a project, and deployment plan consisting of two components sharing a client, server (facet, receptacle) interface. Then, I placed them in different container processes and nodes in a deployment plan. Validate did not catch any issues, and generate descriptors still did (without telling me what deployment plan). The NLS bug seems to be fixed though.
> 
> However, this is not a big enough issue for us that we want to postpone the 1.6 release. We would like to move forward with the 1.6 release and address this in the next release

@j26151 We could not reproduce the issue after creating a model following your instructions. Please find the model we created as an attached file. The validation rule works fine for this model and if we disable the validation rule, xtend code generation creates an error message, as expected. Could you please modify the model and send us back the modified version which produces different results for the emf validation and xtend validation?
 
[issue_08_reopened_working_example.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/3627308/issue_08_reopened_working_example.zip)

**Comment by j26151** [comment]
> * . Write a CX validation rule to detect the issue as part of the **Validate** action. This will have the side effect of highlighting the problematic elements in model tree, and displaying them in the Problems view.

The more involved fix above states that when validating your supplied model, validation should fail, and the offending deployment plan should be highlighted.  I do not see that happening with the 1.6 CX release and the model that you provided.

When generating descriptors, I see the background validation also succeed and the actual generation fails. (I do expect the generation to fail, although the validation should have failed before getting to that point.)

**Comment by elder4p** [comment]
@j26151 : We think we have narrowed it down. The constraint fires in our development environments, but not when installed into RSA. We're trying to figure out why that is. No doubt something both trivial and esoteric.

**Comment by tuhin-github** [comment]
@j26151 Apparently the problem was with the import of the ZML package in the DDS4CCM model.
We fixed the issue via #46 and created a draft milestone "CX4CBDDS 1.6.1 M1" from the "fix_zml_import_in_dds4ccm" branch. Please try the installers in the draft milestone and let us know if this solves the problem.

**Comment by j26151** [comment]
I have validated the bug. It looks like it all works now!. 

Some additional comments about the RPMs. the 1.6.1 M1 tag produces a 1.6.0 rpm, where I would have expected a 1.6.1 rpm. Additionally, I have noticed that it is possible to install both ATCD and AXCIOMA cx rpms on a machine at the same time. Lastly, I think that it would be beneficial for the RPM to have a check in the %pre section to see if RSA is even installed yet, that way, if it isn't, you can exit the installation of the RPM without installing it and failing.

**Comment by elder4p** [comment]
@j26151 : Sorry, the test build that was spun did not include version number updates for the plugins/features from the 1.6.0 release. I will commit updated version numbers the master shortly. This will not affect your install experience. Each build includes the build date as part of the version number, so that a more recent build will always replace an older build, even it the version numbers don' t change.

We will need to discuss the timing of a 1.6.1 release. It will definitely contain this fix. We are also working on #45, which may be a candidate for inclusion, too.

**Comment by elder4p** [comment]
Fixed by pull request #46.
