### ISSUE TITLE
Papyrus] Papyrus CX refactor menu actions

### ISSUE THREAD

**Issue by ysroh** [ZeligsoftDev/CX4CBDDS#85]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
Port menu actions to Papyrus.

NGC to confirm menus list:

Show port type action
Repair worker function action
Repair deployment part action
Show source action
Toggle code tag nature action
Convert struct to field action
Convert field to struct action
Clean references action

**Comment by J17359** [comment]
I can't see a reason we wouldn't want all of the refactor menu items ported over. I don't know what they all do, but I don't think we want to lose functionality here. I know the ones that are super important are:
* Repair worker function action
* Repair deployment part action
* Clean references action
Not sure I've ever used the others but that doesn't mean our customers haven't. If it's really a hard task to port them all over, I can ask around, but my immediate though is that we keep them all.

**Comment by ysroh** [comment]
Sounds good. I will start working on the important actions first.

**Comment by ysroh** [comment]
All actions are now available in Papyrus
