### ISSUE TITLE
CDP generation fails to check for less than or equal in content filters

### ISSUE THREAD

**Issue by elder4p** [ZeligsoftDev/CX4CBDDS#9]
There is a CX4CBDDS bug that puts "<=" into CDP files. This is invalid XML. Add a post CDP generation script/function that corrects this value in content filter elements. "<=" should be "&lt;=" It would be good to check if this situation also occurs with a "<" in a content filter.

**Comment by elder4p** [comment]
There is extensive code to properly encode xml strings, but we are clearly missing something. Attaching a model that reproduces the case.

[BasicPubSub_LessThanBug.zip](https://github.com/ZeligsoftDev/CX4CBDDS/files/3208082/BasicPubSub_LessThanBug.zip)

**Comment by tuhin-github** [comment]
Fixed with #20
