### ISSUE TITLE
Missing Git information in RPM spec file in "papyrus" branch

### ISSUE THREAD

**Issue by J17359** [ZeligsoftDev/CX4CBDDS#90]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When the new spec file was generated for cx-axcioma 2.0.0 based on Papyrus, it looks like the Git information was missed when brought over. 

For example, 
https://github.com/ZeligsoftDev/CX4CBDDS/blob/master/releng/com.zeligsoft.dds4ccm.update.axcioma/rpm_build/zeligsoftCX_axcioma.spec#L13-L23
does not exist in the papyrus spec version.

**Comment by J17359** [comment]
Let me know if you'd prefer me not to add the "project" to issues we log. I just wanted to reiterate that it was a Papyrus-only bug and did not affect the RSA version of CX.

**Comment by ysroh** [comment]
Please do add new issues to the Papyrus project if they are affecting Papyrus only.

 

Thanks.

 

Regards,

 

Young-Soo Roh

Sr. Software Developer

Zeligsoft (2009) Ltd.

**Comment by J17359** [comment]
@elder4p I tested this fix on our packaging infrastructure and saw RPMs named as expected (with githash in name). I'll leave this bug open until you all have a chance to test with Travis CI.

**Comment by J17359** [comment]
Verified your Travis CI also added the git hash to RPM name. Closing this ticket.
