### ISSUE TITLE
 Reduce data space size in Papyrus Diagrams

### ISSUE THREAD

**Issue by j26151** [ZeligsoftDev/CX4CBDDS#91]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
The current size of data spaces is too large. we would like the size to match the size of the border ports. I.E. the size of the data space circle should be able to fit within the port boxes.

**Comment by j26151** [comment]
I cannot edit issues after they are created. This should be papyrus and a major bug.

**Comment by J17359** [comment]
Would you like us to Close the issue once we've tested/confirmed the fix on our end? Or should we just comment that this has fixed our issue and let you move it through to "closed"?

**Comment by ysroh** [comment]
It is fixed. It would be better if you can check this on your side and close this issue once verified. Thanks.

**Comment by J75880** [comment]
I pulled down the fix and tested it by creating an assembly diagram for several of our example models. The dataspaces in the diagram were all smaller and looked exactly how we expected them to. So, this issue passed our testing and will be closed.
