### ISSUE TITLE
Connection lines not fully connecting to dataspaces in diagrams

### ISSUE THREAD

**Issue by J75880** [ZeligsoftDev/CX4CBDDS#93]
# **Issue and tracking information**

### Developer's Actual time spent on fix (hours)  

# **Issue reporter to provide a detailed description of the issue in the space below**
When looking in a diagram with connections from a port to a dataspace, these connections do not appear to fully connect to the dataspace. As in, the connection lines do not fully attach to the dataspace's black dot when connected. This is especially noticeable when trying to move the connection lines around to adjust their placement in the diagram.

**Comment by J75880** [comment]
I cannot edit issues after they are created. This should be papyrus and a major bug.

**Comment by elder4p** [comment]
@J75880 : I've invited you to join the project so that you can modify tickets. After you accept the invite, do you see the gear icon beside Assignees, Labels, Projects, etc... ?

**Comment by J75880** [comment]
@elder4p I accepted the invitation and now I can see gears beside all them except for Projects.

**Comment by elder4p** [comment]
@J75880 : upgraded you from Triage to Write. Do you see the Project 'gear' now?

**Comment by J75880** [comment]
Yes. I should be good now. Thanks!

**Comment by ysroh** [comment]
This is expected behaviour when "snap to grid" is enabled. Please disable the "snap to grid" feature on the preference page "Papyrus -> Diagram" section. You can disable this feature on an existing diagram through the "Rulers and Grid" properties view.

**Comment by J75880** [comment]
Confirmed that disabling "snap to grid" fixes the issue. Will close issue and update preferences on our end.
